DROP TABLE IF EXISTS princeton_review_great_school_major;
DROP TABLE IF EXISTS princeton_review_popular_major;
CREATE TABLE princeton_review_popular_major
(
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL
);

Insert princeton_review_popular_major(Name) values
('Accounting'), 
('Agriculture'),
('Biology'), 
('Business_Finance'),
('Communications'), 
('Computer Science and Computer Engineering'), 
('Criminology'),
('Education'), 
('Engineering'),
('English Literature and Language'),
('Environmental Studies'), 
('Health Services'),
('History'),
('Journalism'), 
('Marketing and Sales'),
('Mathematics'),
('Mechanical Engineering'), 
('Nursing'),
('Political Science and Government'),
('Psychology');


CREATE TABLE princeton_review_great_school_major
(
  Major_Id INT NOT NULL,
  School_Id INT NOT NULL,
  School_Name VARCHAR(80),
  Primary Key (Major_Id, School_Id),
  FOREIGN KEY (Major_Id) REFERENCES princeton_review_popular_major (Id),
  FOREIGN KEY (School_Id) REFERENCES school (Id)
);

Insert princeton_review_great_school_major values(1, 2046, 'Alfred University');
Insert princeton_review_great_school_major values(1, 142, 'Auburn University');
Insert princeton_review_great_school_major values(1, 10000, 'Babson College');
Insert princeton_review_great_school_major values(1, 76, 'Baylor University');
Insert princeton_review_great_school_major values(1, 1119, 'Birmingham-Southern College');
Insert princeton_review_great_school_major values(1, 37, 'Boston College');
Insert princeton_review_great_school_major values(1, 57, 'Boston University');
Insert princeton_review_great_school_major values(1, 79, 'Brigham Young University-Provo');
Insert princeton_review_great_school_major values(1, 1031, 'Bucknell University');
Insert princeton_review_great_school_major values(1, 1120, 'Calvin College');
Insert princeton_review_great_school_major values(1, 1008, 'Claremont McKenna College');
Insert princeton_review_great_school_major values(1, 68, 'Clemson University');
Insert princeton_review_great_school_major values(1, 5011, 'College of Charleston');
Insert princeton_review_great_school_major values(1, 13, 'Cornell University');
Insert princeton_review_great_school_major values(1, 133, 'DePaul University');
Insert princeton_review_great_school_major values(1, 108, 'Drexel University');
Insert princeton_review_great_school_major values(1, 130, 'Duquesne University');
Insert princeton_review_great_school_major values(1, 5000, 'Elon University');
Insert princeton_review_great_school_major values(1, 18, 'Emory University');
Insert princeton_review_great_school_major values(1, 69, 'Fordham University');
Insert princeton_review_great_school_major values(1, 24, 'Georgetown University');
Insert princeton_review_great_school_major values(1, 75, 'Indiana University-Bloomington');
Insert princeton_review_great_school_major values(1, 86, 'Iowa State University');
Insert princeton_review_great_school_major values(1, 5007, 'James Madison University');
Insert princeton_review_great_school_major values(1, 2019, 'Le Moyne College');
Insert princeton_review_great_school_major values(1, 31, 'Lehigh University');
Insert princeton_review_great_school_major values(1, 84, 'Marquette University');
Insert princeton_review_great_school_major values(1, 72, 'Michigan State University');
Insert princeton_review_great_school_major values(1, 34, 'New York University');
Insert princeton_review_great_school_major values(1, 15, 'Northwestern University');
Insert princeton_review_great_school_major values(1, 48, 'Pennsylvania State University-University Park');
Insert princeton_review_great_school_major values(1, 55, 'Pepperdine University');
Insert princeton_review_great_school_major values(1, 2022, 'Rider University');
Insert princeton_review_great_school_major values(1, 2006, 'Rochester Institute of Technology');
Insert princeton_review_great_school_major values(1, 134, 'Seton Hall University');
Insert princeton_review_great_school_major values(1, 2061, 'Suffolk University');
Insert princeton_review_great_school_major values(1, 129, 'Temple University');
Insert princeton_review_great_school_major values(1, 62, 'Texas A&M University-College Station');
Insert princeton_review_great_school_major values(1, 189, 'University of Houston');
Insert princeton_review_great_school_major values(1, 40, 'University of Illinois-Urbana-Champaign');
Insert princeton_review_great_school_major values(1, 26, 'University of Michigan-Ann Arbor');
Insert princeton_review_great_school_major values(1, 5, 'University of Pennsylvania');
Insert princeton_review_great_school_major values(1, 27, 'University of Southern California');
Insert princeton_review_great_school_major values(1, 45, 'University of Texas-Austin');
Insert princeton_review_great_school_major values(1, 147, 'University of Texas-Dallas');

Insert princeton_review_great_school_major values(2, 3091, 'Angelo State University');
Insert princeton_review_great_school_major values(2, 127, 'Arizona State University-Tempe');
Insert princeton_review_great_school_major values(2, 142, 'Auburn University');
Insert princeton_review_great_school_major values(2, 1067,'Berea College');
Insert princeton_review_great_school_major values(2, 3056,'California State University-Stanislaus');
Insert princeton_review_great_school_major values(2, 68, 'Clemson University');
Insert princeton_review_great_school_major values(2, 1081,'College of the Atlantic');
Insert princeton_review_great_school_major values(2, 8003, 'College of the Ozarks');
Insert princeton_review_great_school_major values(2, 125, 'Colorado State University');
Insert princeton_review_great_school_major values(2, 13, 'Cornell University');
Insert princeton_review_great_school_major values(2, 1197, 'Green Mountain College');
Insert princeton_review_great_school_major values(2, 86, 'Iowa State University');
Insert princeton_review_great_school_major values(2, 123, 'Kansas State University');
Insert princeton_review_great_school_major values(2, 138, 'Louisiana State University-Baton Rouge');
Insert princeton_review_great_school_major values(2, 72, 'Michigan State University');
Insert princeton_review_great_school_major values(2, 89,'North Carolina State University-Raleigh');
Insert princeton_review_great_school_major values(2, 48, 'Pennsylvania State University-University Park');
Insert princeton_review_great_school_major values(2, 3084, 'Prescott College');
Insert princeton_review_great_school_major values(2, 66, 'Purdue University-West Lafayette');
Insert princeton_review_great_school_major values(2, 62, 'Texas A&M University-College Station');
Insert princeton_review_great_school_major values(2, 107,'Texas Christian University');
Insert princeton_review_great_school_major values(2, 4007, 'Truman State University');
Insert princeton_review_great_school_major values(2, 9009, 'Tuskegee University');
Insert princeton_review_great_school_major values(2, 105,'University of Arizona');
Insert princeton_review_great_school_major values(2, 126,'University of Arkansas-Fayetteville');
Insert princeton_review_great_school_major values(2, 43, 'University of California-Davis');
Insert princeton_review_great_school_major values(2, 49,'University of Florida');
Insert princeton_review_great_school_major values(2, 60, 'University of Georgia');
Insert princeton_review_great_school_major values(2, 166, 'University of Hawaii-Manoa');
Insert princeton_review_great_school_major values(2, 171, 'University of Idaho');
Insert princeton_review_great_school_major values(2, 40, 'University of Illinois-Urbana-Champaign');
Insert princeton_review_great_school_major values(2, 120, 'University of Kentucky');
Insert princeton_review_great_school_major values(2, 173, 'University of Maine');
Insert princeton_review_great_school_major values(2, 56, 'University of Maryland-College Park');
Insert princeton_review_great_school_major values(2, 96, 'University of Massachusetts-Amherst');
Insert princeton_review_great_school_major values(2, 92, 'University of Missouri-Columbia');
Insert princeton_review_great_school_major values(2, 95, 'University of Nebraska-Lincon');
Insert princeton_review_great_school_major values(2, 101, 'University of Tennessee');
Insert princeton_review_great_school_major values(2, 98, 'University of Vermont');
Insert princeton_review_great_school_major values(2, 38, 'University of Wisconsin-Madison');
Insert princeton_review_great_school_major values(2, 174, 'University of Wyoming');
Insert princeton_review_great_school_major values(2, 119, 'Washington State University');
Insert princeton_review_great_school_major values(2, 179, 'West Virginia University');

Insert princeton_review_great_school_major values(3, 1066, 'Agnes Scott College');
Insert princeton_review_great_school_major values(3, 1099, 'Albion College');
Insert princeton_review_great_school_major values(3, 1078, 'Austin College');
Insert princeton_review_great_school_major values(3, 1071, 'Allegheny College');
Insert princeton_review_great_school_major values(3, 76, 'Baylor University');
Insert princeton_review_great_school_major values(3, 32, 'Brandeis University');
Insert princeton_review_great_school_major values(3, 1007, 'Carleton College');
Insert princeton_review_great_school_major values(3, 5014, 'Christopher Newport University');
Insert princeton_review_great_school_major values(3, 1018, 'Colby College');
Insert princeton_review_great_school_major values(3, 13, 'Cornell University');
Insert princeton_review_great_school_major values(3, 108, 'Drexel University');
Insert princeton_review_great_school_major values(3, 8,'Duke University');
Insert princeton_review_great_school_major values(3, 1159, 'Guilford College');
Insert princeton_review_great_school_major values(3, 2,'Harvard University');
Insert princeton_review_great_school_major values(3, 1011, 'Haverford College');
Insert princeton_review_great_school_major values(3, 102, 'Howard University');
Insert princeton_review_great_school_major values(3, 1072, 'Illinois Wesleyan University');
Insert princeton_review_great_school_major values(3, 75,'Indiana University-Bloomington');
Insert princeton_review_great_school_major values(3, 16, 'Johns Hopkins University');
Insert princeton_review_great_school_major values(3, 138, 'Louisiana State University-Baton Rouge');
Insert princeton_review_great_school_major values(3, 111, 'Loyola University of Chicago');
Insert princeton_review_great_school_major values(3, 7,'Massachusetts Institute of Technology');
Insert princeton_review_great_school_major values(3, 1094, 'Millsaps College');
Insert princeton_review_great_school_major values(3, 1034, 'Mount Holyoke College');
Insert princeton_review_great_school_major values(3, 58, 'Ohio State University-Columbus');
Insert princeton_review_great_school_major values(3, 116, 'Ohio University');
Insert princeton_review_great_school_major values(3, 1005, 'Pomona College');
Insert princeton_review_great_school_major values(3, 1095, 'Reed College');
Insert princeton_review_great_school_major values(3, 17, 'Rice University');
Insert princeton_review_great_school_major values(3, 1002, 'Swarthmore College');
Insert princeton_review_great_school_major values(3, 129, 'Temple University');
Insert princeton_review_great_school_major values(3, 62, 'Texas A&M University-College Station');
Insert princeton_review_great_school_major values(3, 6000, 'United States Coast Guard Academy');
Insert princeton_review_great_school_major values(3, 43, 'University of California-Davis');
Insert princeton_review_great_school_major values(3, 39,'University of California-San Diego');
Insert princeton_review_great_school_major values(3, 10, 'University of Chicago');
Insert princeton_review_great_school_major values(3, 3014, 'University of Dallas');
Insert princeton_review_great_school_major values(3, 73, 'University of Delaware');
Insert princeton_review_great_school_major values(3, 88, 'University of Denver');
Insert princeton_review_great_school_major values(3, 189, 'University of Houston');
Insert princeton_review_great_school_major values(3, 182, 'University of New Mexico');
Insert princeton_review_great_school_major values(3, 104, 'University of the Pacific');
Insert princeton_review_great_school_major values(3, 1088, 'Wofford College');
Insert princeton_review_great_school_major values(3, 1234, 'Xavier University of Louisiana');

Insert princeton_review_great_school_major values(4, 127, 'Arizona State University-Tempe');
Insert princeton_review_great_school_major values(4, 10000, 'Babson College');
Insert princeton_review_great_school_major values(4, 2002, 'Bentley University');
Insert princeton_review_great_school_major values(4, 37, 'Boston College');
Insert princeton_review_great_school_major values(4, 2010, 'Bryant University');
Insert princeton_review_great_school_major values(4, 22, 'Carnegie Mellon University');
Insert princeton_review_great_school_major values(4, 6014, 'Champlain College');
Insert princeton_review_great_school_major values(4, 5014, 'Christopher Newport University');
Insert princeton_review_great_school_major values(4, 2032, 'CUNY-Baruch College');
Insert princeton_review_great_school_major values(4, 2082, 'CUNY-Brooklyn College');
Insert princeton_review_great_school_major values(4, 13, 'Cornell University');
Insert princeton_review_great_school_major values(4, 133, 'DePaul University');
Insert princeton_review_great_school_major values(4, 18, 'Emory University');
Insert princeton_review_great_school_major values(4, 112, 'Florida State University');
Insert princeton_review_great_school_major values(4, 75, 'Indiana University-Bloomington');
Insert princeton_review_great_school_major values(4, 86, 'Iowa State University');
Insert princeton_review_great_school_major values(4, 31, 'Lehigh University');
Insert princeton_review_great_school_major values(4, 7,'Massachusetts Institute of Technology');
Insert princeton_review_great_school_major values(4, 70, 'Miami University-Oxford');
Insert princeton_review_great_school_major values(4, 72, 'Michigan State University');
Insert princeton_review_great_school_major values(4, 34, 'New York University');
Insert princeton_review_great_school_major values(4, 15, 'Northwestern University');
Insert princeton_review_great_school_major values(4, 116, 'Ohio University');
Insert princeton_review_great_school_major values(4, 232, 'Portland State University');
Insert princeton_review_great_school_major values(4, 17, 'Rice University');
Insert princeton_review_great_school_major values(4, 1144, 'Roanoke College');
Insert princeton_review_great_school_major values(4, 3005, 'Seattle University');
Insert princeton_review_great_school_major values(4, 21, 'University of California-Berkeley');
Insert princeton_review_great_school_major values(4, 25, 'University of California-Los Angeles');
Insert princeton_review_great_school_major values(4, 10, 'University of Chicago');
Insert princeton_review_great_school_major values(4, 49,'University of Florida');
Insert princeton_review_great_school_major values(4, 189, 'University of Houston');
Insert princeton_review_great_school_major values(4, 40, 'University of Illinois-Urbana-Champaign');
Insert princeton_review_great_school_major values(4, 26, 'University of Michigan-Ann Arbor');
Insert princeton_review_great_school_major values(4, 20, 'University of Notre Dame');
Insert princeton_review_great_school_major values(4, 5, 'University of Pennsylvania');
Insert princeton_review_great_school_major values(4, 1033, 'University of Richmond');
Insert princeton_review_great_school_major values(4, 27, 'University of Southern California');
Insert princeton_review_great_school_major values(4, 45, 'University of Texas-Austin');

Insert princeton_review_great_school_major values(5, 76, 'Baylor University');
Insert princeton_review_great_school_major values(5, 37, 'Boston College');
Insert princeton_review_great_school_major values(5, 57, 'Boston University');
Insert princeton_review_great_school_major values(5, 4003, 'Bradley University');
Insert princeton_review_great_school_major values(5, 2047, 'CUNY-Hunter College');
Insert princeton_review_great_school_major values(5, 68, 'Clemson University');
Insert princeton_review_great_school_major values(5, 5011, 'College of Charleston');
Insert princeton_review_great_school_major values(5, 13, 'Cornell University');
Insert princeton_review_great_school_major values(5, 1054, 'Denison University');
Insert princeton_review_great_school_major values(5, 133, 'DePaul University');
Insert princeton_review_great_school_major values(5, 130, 'Duquesne University');
Insert princeton_review_great_school_major values(5, 1127, 'Eckerd College');
Insert princeton_review_great_school_major values(5, 5000, 'Elon University');
Insert princeton_review_great_school_major values(5, 2009, 'Emerson College');
Insert princeton_review_great_school_major values(5, 2005, 'Fairfield University');
Insert princeton_review_great_school_major values(5, 69, 'Fordham University');
Insert princeton_review_great_school_major values(5, 3003, 'Gonzaga University');
Insert princeton_review_great_school_major values(5, 1079, 'Gustavus Adolphus College');
Insert princeton_review_great_school_major values(5, 1108, 'Hollins University');
Insert princeton_review_great_school_major values(5, 75, 'Indiana University-Bloomington');
Insert princeton_review_great_school_major values(5, 86, 'Iowa State University');
Insert princeton_review_great_school_major values(5, 2008, 'Ithaca College');
Insert princeton_review_great_school_major values(5, 5007, 'James Madison University');
Insert princeton_review_great_school_major values(5, 1109, 'Lake Forest College');
Insert princeton_review_great_school_major values(5, 5012, 'Loyola University New Orleans');
Insert princeton_review_great_school_major values(5, 72, 'Michigan State University');
Insert princeton_review_great_school_major values(5, 1075, 'Muhlenberg College');
Insert princeton_review_great_school_major values(5, 34, 'New York University');
Insert princeton_review_great_school_major values(5, 15, 'Northwestern University');
Insert princeton_review_great_school_major values(5, 55, 'Pepperdine University');
Insert princeton_review_great_school_major values(5, 2011, 'Quinnipiac University');
Insert princeton_review_great_school_major values(5, 1117, 'Ripon College');
Insert princeton_review_great_school_major values(5, 2071, 'Salisbury University');
Insert princeton_review_great_school_major values(5, 134, 'Seton Hall University');
Insert princeton_review_great_school_major values(5, 155, 'St. John-s University');
Insert princeton_review_great_school_major values(5, 9, 'Stanford University');
Insert princeton_review_great_school_major values(5, 2061, 'Suffolk University');
Insert princeton_review_great_school_major values(5, 51, 'Syracuse University');
Insert princeton_review_great_school_major values(5, 39, 'University of California-San Diego');
Insert princeton_review_great_school_major values(5, 46, 'University of California-Santa Barbara');
Insert princeton_review_great_school_major values(5, 64, 'University of Iowa');
Insert princeton_review_great_school_major values(5, 56, 'University of Maryland-College Park');
Insert princeton_review_great_school_major values(5, 27, 'University of Southern California');
Insert princeton_review_great_school_major values(5, 45, 'University of Texas-Austin');
Insert princeton_review_great_school_major values(5, 147, 'University of Texas-Dallas');
Insert princeton_review_great_school_major values(5, 132, 'University of Utah');
Insert princeton_review_great_school_major values(5, 23, 'University of Virginia');
Insert princeton_review_great_school_major values(5, 12, 'Washington University in St. Louis');


Insert princeton_review_great_school_major values(6, 142, 'Auburn University');
Insert princeton_review_great_school_major values(6, 57, 'Boston University');
Insert princeton_review_great_school_major values(6, 4003, 'Bradley University');
Insert princeton_review_great_school_major values(6, 14,'Brown University');
Insert princeton_review_great_school_major values(6, 6, 'California Institute of Technology');
Insert princeton_review_great_school_major values(6, 22, 'Carnegie Mellon University');
Insert princeton_review_great_school_major values(6, 6014, 'Champlain College');
Insert princeton_review_great_school_major values(6, 68, 'Clemson University');
Insert princeton_review_great_school_major values(6, 108, 'Drexel University');
Insert princeton_review_great_school_major values(6, 112, 'Florida State University');
Insert princeton_review_great_school_major values(6, 139, 'George Mason University');
Insert princeton_review_great_school_major values(6, 36,'Georgia Institute of Technology');
Insert princeton_review_great_school_major values(6, 3003, 'Gonzaga University');
Insert princeton_review_great_school_major values(6, 5018, 'Hampton University');
Insert princeton_review_great_school_major values(6, 1014, 'Harvey Mudd College');
Insert princeton_review_great_school_major values(6, 100, 'Illinois Institute of Technology');
Insert princeton_review_great_school_major values(6, 86, 'Iowa State University');
Insert princeton_review_great_school_major values(6, 16, 'Johns Hopkins University');
Insert princeton_review_great_school_major values(6, 31, 'Lehigh University');
Insert princeton_review_great_school_major values(6, 7, 'Massachusetts Institute of Technology');
Insert princeton_review_great_school_major values(6, 72, 'Michigan State University');
Insert princeton_review_great_school_major values(6, 117, 'Missouri University of Science & Technology');
Insert princeton_review_great_school_major values(6, 122, 'New Jersey Institute of Technology');
Insert princeton_review_great_school_major values(6, 97, 'Northeastern University');
Insert princeton_review_great_school_major values(6, 15, 'Northwestern University');
Insert princeton_review_great_school_major values(6, 48, 'Pennsylvania State University-University Park');
Insert princeton_review_great_school_major values(6, 1,'Princeton University');
Insert princeton_review_great_school_major values(6, 17, 'Rice University');
Insert princeton_review_great_school_major values(6, 44, 'Rensselaer Polytechnic Institute');
Insert princeton_review_great_school_major values(6, 3005, 'Seattle University');
Insert princeton_review_great_school_major values(6, 9, 'Stanford University');
Insert princeton_review_great_school_major values(6, 82, 'SUNY-Binghamton');
Insert princeton_review_great_school_major values(6, 62, 'Texas A&M University-College Station');
Insert princeton_review_great_school_major values(6, 1030, 'United States Air Force Academy');
Insert princeton_review_great_school_major values(6, 105,'University of Arizona');
Insert princeton_review_great_school_major values(6, 21, 'University of California-Berkeley');
Insert princeton_review_great_school_major values(6, 25, 'University of California-Los Angeles');
Insert princeton_review_great_school_major values(6, 103, 'University of California-Riverside');
Insert princeton_review_great_school_major values(6, 40, 'University of Illinois-Urbana-Champaign');
Insert princeton_review_great_school_major values(6, 156,'University of Maryland-Baltimore County');
Insert princeton_review_great_school_major values(6, 96, 'University of Massachusetts-Amherst');
Insert princeton_review_great_school_major values(6, 26, 'University of Michigan-Ann Arbor');
Insert princeton_review_great_school_major values(6, 42, 'University of Washington');
Insert princeton_review_great_school_major values(6, 63, 'Worcester Polytechnic Institute');



Insert princeton_review_great_school_major values(7, 87, 'American University');
Insert princeton_review_great_school_major values(7, 142, 'Auburn University');
Insert princeton_review_great_school_major values(7, 112, 'Florida State University');
Insert princeton_review_great_school_major values(7, 1159, 'Guilford College');
Insert princeton_review_great_school_major values(7, 217, 'Indiana University of Pennsylvania');
Insert princeton_review_great_school_major values(7, 89,'North Carolina State University-Raleigh');
Insert princeton_review_great_school_major values(7, 58, 'Ohio State University-Columbus');
Insert princeton_review_great_school_major values(7, 116, 'Ohio University');
Insert princeton_review_great_school_major values(7, 2011, 'Quinnipiac University');
Insert princeton_review_great_school_major values(7, 2061, 'Suffolk University');
Insert princeton_review_great_school_major values(7, 73, 'University of Delaware');
Insert princeton_review_great_school_major values(7, 88, 'University of Denver');
Insert princeton_review_great_school_major values(7, 56, 'University of Maryland-College Park');
Insert princeton_review_great_school_major values(7, 52, 'University of Miami');
Insert princeton_review_great_school_major values(7, 109, 'University of New Hampshire');
Insert princeton_review_great_school_major values(7, 158, 'University of South Florida');
Insert princeton_review_great_school_major values(7, 132, 'University of Utah');
Insert princeton_review_great_school_major values(7, 4004, 'Valparaiso University');
Insert princeton_review_great_school_major values(7, 1230, 'Virginia Wesleyan College');
Insert princeton_review_great_school_major values(7, 1132, 'Whittier College');


Insert princeton_review_great_school_major values(8, 142, 'Auburn University');
Insert princeton_review_great_school_major values(8, 1028, 'Barnard College');
Insert princeton_review_great_school_major values(8, 1031, 'Bucknell University');
Insert princeton_review_great_school_major values(8, 2082, 'CUNY-Brooklyn College');
Insert princeton_review_great_school_major values(8, 2047, 'CUNY-Hunter College');
Insert princeton_review_great_school_major values(8, 1019, 'Colgate University');
Insert princeton_review_great_school_major values(8, 8003, 'College of the Ozarks');
Insert princeton_review_great_school_major values(8, 33, 'College of William and Mary');
Insert princeton_review_great_school_major values(8, 4,'Columbia University');
Insert princeton_review_great_school_major values(8, 1093, 'Cornell College');
Insert princeton_review_great_school_major values(8, 13, 'Cornell University');
Insert princeton_review_great_school_major values(8, 130, 'Duquesne University');
Insert princeton_review_great_school_major values(8, 5000, 'Elon University');
Insert princeton_review_great_school_major values(8, 3003, 'Gonzaga University');
Insert princeton_review_great_school_major values(8, 1112, 'Goucher College');
Insert princeton_review_great_school_major values(8, 1068, 'Hillsdale College');
Insert princeton_review_great_school_major values(8, 75, 'Indiana University-Bloomington');
Insert princeton_review_great_school_major values(8, 1073, 'Knox College');
Insert princeton_review_great_school_major values(8, 3002, 'Loyola Marymount University');
Insert princeton_review_great_school_major values(8, 84, 'Marquette University');
/*Insert princeton_review_great_school_major values(8, -2, 'McGill University');*/
Insert princeton_review_great_school_major values(8, 70, 'Miami University-Oxford');
Insert princeton_review_great_school_major values(8, 2036, 'Monmouth University');
Insert princeton_review_great_school_major values(8, 2029, 'Nazareth College');
Insert princeton_review_great_school_major values(8, 34, 'New York University');
Insert princeton_review_great_school_major values(8, 97, 'Northeastern University');
Insert princeton_review_great_school_major values(8, 15, 'Northwestern University');
Insert princeton_review_great_school_major values(8, 58, 'Ohio State University-Columbus');
Insert princeton_review_great_school_major values(8, 3084, 'Prescott College');
Insert princeton_review_great_school_major values(8, 2015, 'Simmons College');
Insert princeton_review_great_school_major values(8, 1037, 'Skidmore College');
Insert princeton_review_great_school_major values(8, 1015, 'Smith College');
Insert princeton_review_great_school_major values(8, 3000, 'Trinity University');
Insert princeton_review_great_school_major values(8, 173, 'University of Maine');
Insert princeton_review_great_school_major values(8, 146, 'University of Mississippi');
Insert princeton_review_great_school_major values(8, 251, 'University of Montana');
Insert princeton_review_great_school_major values(8, 19, 'Vanderbilt University');
Insert princeton_review_great_school_major values(8, 2000, 'Villanova University');
Insert princeton_review_great_school_major values(8, 2027, 'Wagner College');
Insert princeton_review_great_school_major values(8, 1006, 'Wellesley College');
Insert princeton_review_great_school_major values(8, 1125, 'Westminster College');
Insert princeton_review_great_school_major values(8, 1162, 'William Jewell College');
Insert princeton_review_great_school_major values(8, 4005, 'Xavier University');


Insert princeton_review_great_school_major values(9, 6, 'California Institute of Technology');
Insert princeton_review_great_school_major values(9, 22, 'Carnegie Mellon University');
Insert princeton_review_great_school_major values(9, 4, 'Columbia University');
Insert princeton_review_great_school_major values(9, 6001, 'Cooper Union');
Insert princeton_review_great_school_major values(9, 13, 'Cornell University');
Insert princeton_review_great_school_major values(9, 108, 'Drexel University');
Insert princeton_review_great_school_major values(9, 8,'Duke University');
Insert princeton_review_great_school_major values(9, 10001, 'Franklin W. Olin College of Engineering');
Insert princeton_review_great_school_major values(9, 36,'Georgia Institute of Technology');
Insert princeton_review_great_school_major values(9, 2,'Harvard University');
Insert princeton_review_great_school_major values(9, 1014, 'Harvey Mudd College');
Insert princeton_review_great_school_major values(9, 100, 'Illinois Institute of Technology');
Insert princeton_review_great_school_major values(9, 16, 'Johns Hopkins University');
Insert princeton_review_great_school_major values(9, 7, 'Massachusetts Institute of Technology');
Insert princeton_review_great_school_major values(9, 117, 'Missouri University of Science & Technology');
Insert princeton_review_great_school_major values(9, 7005, 'Montana Tech of the University of Montana');
Insert princeton_review_great_school_major values(9, 48, 'Pennsylvania State University-University Park');
Insert princeton_review_great_school_major values(9, 1,'Princeton University');
Insert princeton_review_great_school_major values(9, 66, 'Purdue University-West Lafayette');
Insert princeton_review_great_school_major values(9, 44, 'Rensselaer Polytechnic Institute');
Insert princeton_review_great_school_major values(9, 9, 'Stanford University');
Insert princeton_review_great_school_major values(9, 77, 'Stevens Institute of Technology');
Insert princeton_review_great_school_major values(9, 62, 'Texas A&M University-College Station');
Insert princeton_review_great_school_major values(9, 6002, 'United States Merchant Marine Academy');
Insert princeton_review_great_school_major values(9, 21, 'University of California-Berkeley');
Insert princeton_review_great_school_major values(9, 25, 'University of California-Los Angeles');
Insert princeton_review_great_school_major values(9, 45, 'University of Texas-Austin');
Insert princeton_review_great_school_major values(9, 38, 'University of Wisconsin-Madison');
Insert princeton_review_great_school_major values(9, 71, 'Virginia Tech');
Insert princeton_review_great_school_major values(9, 10002, 'Webb Institute');
Insert princeton_review_great_school_major values(9, 63, 'Worcester Polytechnic Institute');


Insert princeton_review_great_school_major values(10, 1001, 'Amherst College');
Insert princeton_review_great_school_major values(10, 142, 'Auburn University');
Insert princeton_review_great_school_major values(10, 1044, 'Bard College');
Insert princeton_review_great_school_major values(10, 1024, 'Bates College');
Insert princeton_review_great_school_major values(10, 37, 'Boston College');
Insert princeton_review_great_school_major values(10, 57, 'Boston University');
Insert princeton_review_great_school_major values(10, 1025, 'Bryn Mawr College');
Insert princeton_review_great_school_major values(10, 2047, 'CUNY-Hunter College');
Insert princeton_review_great_school_major values(10, 1008, 'Claremont McKenna College');
Insert princeton_review_great_school_major values(10, 68, 'Clemson University');
Insert princeton_review_great_school_major values(10, 1018, 'Colby College');
Insert princeton_review_great_school_major values(10, 1019, 'Colgate University');
Insert princeton_review_great_school_major values(10, 4,'Columbia University');
Insert princeton_review_great_school_major values(10, 13, 'Cornell University');
Insert princeton_review_great_school_major values(10, 11, 'Dartmouth College');
Insert princeton_review_great_school_major values(10, 1054, 'Denison University');
Insert princeton_review_great_school_major values(10, 8,'Duke University');
Insert princeton_review_great_school_major values(10, 18, 'Emory University');
Insert princeton_review_great_school_major values(10, 69, 'Fordham University');
Insert princeton_review_great_school_major values(10, 5007, 'James Madison University');
Insert princeton_review_great_school_major values(10, 1048, 'Gettysburg College');
Insert princeton_review_great_school_major values(10, 1158, 'Gordon College');
Insert princeton_review_great_school_major values(10, 1020, 'Grinnell College');
Insert princeton_review_great_school_major values(10, 2,'Harvard University');
Insert princeton_review_great_school_major values(10, 16, 'Johns Hopkins University');
Insert princeton_review_great_school_major values(10, 1065, 'Kalamazoo College');
Insert princeton_review_great_school_major values(10, 1027, 'Kenyon College');
Insert princeton_review_great_school_major values(10, 1138, 'Marlboro College');
Insert princeton_review_great_school_major values(10, 1023, 'Oberlin College');
Insert princeton_review_great_school_major values(10, 1035, 'Pitzer College');
Insert princeton_review_great_school_major values(10, 1005,'Pomona College');
Insert princeton_review_great_school_major values(10, 1,'Princeton University');
Insert princeton_review_great_school_major values(10, 1095, 'Reed College');
Insert princeton_review_great_school_major values(10, 17, 'Rice University');
Insert princeton_review_great_school_major values(10, 1049, 'Sewanee-University of the South');
Insert princeton_review_great_school_major values(10, 1015, 'Smith College');
Insert princeton_review_great_school_major values(10, 9,'Stanford University');
Insert princeton_review_great_school_major values(10, 1096, 'St. Mary-s College of Maryland');
Insert princeton_review_great_school_major values(10, 137, 'University at Albany-SUNY');
Insert princeton_review_great_school_major values(10, 51, 'Syracuse University');
Insert princeton_review_great_school_major values(10, 29, 'Tufts University');
Insert princeton_review_great_school_major values(10, 21, 'University of California-Berkeley');
Insert princeton_review_great_school_major values(10, 10, 'University of Chicago');
Insert princeton_review_great_school_major values(10, 26, 'University of Michigan-Ann Arbor');
Insert princeton_review_great_school_major values(10, 150, 'University of North Carolina-Asheville');
Insert princeton_review_great_school_major values(10, 20, 'University of Notre Dame');
Insert princeton_review_great_school_major values(10, 132, 'University of Utah');
Insert princeton_review_great_school_major values(10, 1012, 'Vassar College');
Insert princeton_review_great_school_major values(10, 12, 'Washington University in St. Louis');
Insert princeton_review_great_school_major values(10, 1006, 'Wellesley College');
Insert princeton_review_great_school_major values(10, 1000, 'Williams College');
Insert princeton_review_great_school_major values(10, 3,'Yale University');



Insert princeton_review_great_school_major values(11, 1071, 'Allegheny College');
Insert princeton_review_great_school_major values(11, 1024, 'Bates College');
Insert princeton_review_great_school_major values(11, 1003, 'Bowdoin College');
Insert princeton_review_great_school_major values(11, 9014, 'Catawba College');
Insert princeton_review_great_school_major values(11, 1018, 'Colby College');
Insert princeton_review_great_school_major values(11, 1081, 'College of the Atlantic');
Insert princeton_review_great_school_major values(11, 1026, 'Colorado College');
Insert princeton_review_great_school_major values(11, 1039, 'Dickinson College');
Insert princeton_review_great_school_major values(11, 1127, 'Eckerd College');
Insert princeton_review_great_school_major values(11, 18, 'Emory University');
Insert princeton_review_great_school_major values(11, 3035, 'Evergreen State College');
Insert princeton_review_great_school_major values(11, 1197, 'Green Mountain College');
Insert princeton_review_great_school_major values(11, 2,'Harvard University');
Insert princeton_review_great_school_major values(11, 1063, 'Hobart and William Smith Colleges');
Insert princeton_review_great_school_major values(11, 1105, 'Juniata College');
Insert princeton_review_great_school_major values(11, 1004, 'Middlebury College');
Insert princeton_review_great_school_major values(11, 1083, 'New College of Florida');
Insert princeton_review_great_school_major values(11, 97, 'Northeastern University');
Insert princeton_review_great_school_major values(11, 1042, 'Occidental College');
Insert princeton_review_great_school_major values(11, 1035, 'Pitzer College');
Insert princeton_review_great_school_major values(11, 1005,'Pomona College');
Insert princeton_review_great_school_major values(11, 232, 'Portland State University');
Insert princeton_review_great_school_major values(11, 3084, 'Prescott College');
Insert princeton_review_great_school_major values(11, 1049, 'Sewanee-University of the South');
Insert princeton_review_great_school_major values(11, 3047, 'Sonoma State University');
Insert princeton_review_great_school_major values(11, 82, 'SUNY-Binghamton');
Insert princeton_review_great_school_major values(11, 90, 'SUNY College of Environmental Science and Forestry');
Insert princeton_review_great_school_major values(11, 21, 'University of California-Berkeley');
Insert princeton_review_great_school_major values(11, 81, 'University of California-Santa Cruz');
Insert princeton_review_great_school_major values(11, 80, 'University of Colorado-Boulder');
Insert princeton_review_great_school_major values(11, 171, 'University of Idaho');
Insert princeton_review_great_school_major values(11, 251, 'University of Montana');
Insert princeton_review_great_school_major values(11, 109, 'University of New Hampshire');
Insert princeton_review_great_school_major values(11, 150, 'University of North Carolina-Asheville');
Insert princeton_review_great_school_major values(11, 28, 'University of North Carolina-Chapel Hill');
Insert princeton_review_great_school_major values(11, 114, 'University of Oregon');
Insert princeton_review_great_school_major values(11, 3011, 'University of Redlands');
Insert princeton_review_great_school_major values(11, 104, 'University of the Pacific');
Insert princeton_review_great_school_major values(11, 98, 'University of Vermont');
Insert princeton_review_great_school_major values(11, 1165, 'Warren Wilson College');
Insert princeton_review_great_school_major values(11, 1103, 'Washington College');


Insert princeton_review_great_school_major values(12, 5013, 'Bellarmine University');
Insert princeton_review_great_school_major values(12, 57, 'Boston University');
Insert princeton_review_great_school_major values(12, 68, 'Clemson University');
Insert princeton_review_great_school_major values(12, 1168, 'College of Idaho');
Insert princeton_review_great_school_major values(12, 8003, 'College of the Ozarks');
Insert princeton_review_great_school_major values(12, 4000, 'Creighton University');
Insert princeton_review_great_school_major values(12, 108, 'Drexel University');
Insert princeton_review_great_school_major values(12, 130, 'Duquesne University');
Insert princeton_review_great_school_major values(12, 2005, 'Fairfield University');
Insert princeton_review_great_school_major values(12, 1048, 'Gettysburg College');
Insert princeton_review_great_school_major values(12, 1079, 'Gustavus Adolphus College');
Insert princeton_review_great_school_major values(12, 5018, 'Hampton University');
Insert princeton_review_great_school_major values(12, 102, 'Howard University');
Insert princeton_review_great_school_major values(12, 2008, 'Ithaca College');
Insert princeton_review_great_school_major values(12, 16, 'Johns Hopkins University');
Insert princeton_review_great_school_major values(12, 1065, 'Kalamazoo College');
Insert princeton_review_great_school_major values(12, 111, 'Loyola University of Chicago');
Insert princeton_review_great_school_major values(12, 2041, 'Marywood University');
Insert princeton_review_great_school_major values(12, 2036, 'Monmouth University');
Insert princeton_review_great_school_major values(12, 2029, 'Nazareth College');
Insert princeton_review_great_school_major values(12, 97, 'Northeastern University');
Insert princeton_review_great_school_major values(12, 116, 'Ohio University');
Insert princeton_review_great_school_major values(12, 66, 'Purdue University-West Lafayette');
Insert princeton_review_great_school_major values(12, 2011, 'Quinnipiac University');
Insert princeton_review_great_school_major values(12, 2044, 'Sacred Heart University');
Insert princeton_review_great_school_major values(12, 1114, 'St. Anselm College');
Insert princeton_review_great_school_major values(12, 83, 'Saint Louis University');
Insert princeton_review_great_school_major values(12, 134, 'Seton Hall University');
Insert princeton_review_great_school_major values(12, 2015, 'Simmons College');
Insert princeton_review_great_school_major values(12, 99, 'SUNY-Stony Brook');
Insert princeton_review_great_school_major values(12, 8029, 'Stephens College');
Insert princeton_review_great_school_major values(12, 2061, 'Suffolk University');
Insert princeton_review_great_school_major values(12, 62, 'Texas A&M University-College Station');
Insert princeton_review_great_school_major values(12, 107, 'Texas Christian University');
Insert princeton_review_great_school_major values(12, 50, 'Tulane University');
Insert princeton_review_great_school_major values(12, 152, 'University of Alabama-Birmingham');
Insert princeton_review_great_school_major values(12, 170, 'University of Central Florida');
Insert princeton_review_great_school_major values(12, 145, 'University of Cincinnati');
Insert princeton_review_great_school_major values(12, 49,'University of Florida');
Insert princeton_review_great_school_major values(12, 189, 'University of Houston');
Insert princeton_review_great_school_major values(12, 52, 'University of Miami');
Insert princeton_review_great_school_major values(12, 110, 'University of Oklahoma');
Insert princeton_review_great_school_major values(12, 132, 'University of Utah');
Insert princeton_review_great_school_major values(12, 2027, 'Wagner College');
Insert princeton_review_great_school_major values(12, 12, 'Washington University in St. Louis');
Insert princeton_review_great_school_major values(12, 1125, 'Westminster College');
Insert princeton_review_great_school_major values(12, 1058, 'Wheaton College');
Insert princeton_review_great_school_major values(12, 1162, 'William Jewell College');


Insert princeton_review_great_school_major values(13, 1024, 'Bates College');
Insert princeton_review_great_school_major values(13, 1003, 'Bowdoin College');
Insert princeton_review_great_school_major values(13, 14,'Brown University');
Insert princeton_review_great_school_major values(13, 1045, 'Centre College');
Insert princeton_review_great_school_major values(13, 1019, 'Colgate University');
Insert princeton_review_great_school_major values(13, 1032, 'College of the Holy Cross');
Insert princeton_review_great_school_major values(13, 1061, 'College of Wooster');
Insert princeton_review_great_school_major values(13, 4, 'Columbia University');
Insert princeton_review_great_school_major values(13, 1009, 'Davidson College');
Insert princeton_review_great_school_major values(13, 1111, 'Drew University');
Insert princeton_review_great_school_major values(13, 1051, 'Furman University');
Insert princeton_review_great_school_major values(13, 24, 'Georgetown University');
Insert princeton_review_great_school_major values(13, 1020, 'Grinnell College');
Insert princeton_review_great_school_major values(13, 1107, 'Hampden-Sydney College');
Insert princeton_review_great_school_major values(13, 2,'Harvard University');
Insert princeton_review_great_school_major values(13, 1011, 'Haverford College');
Insert princeton_review_great_school_major values(13, 1068, 'Hillsdale College');
Insert princeton_review_great_school_major values(13, 1027, 'Kenyon College');
Insert princeton_review_great_school_major values(13, 1138, 'Marlboro College');
Insert princeton_review_great_school_major values(13, 1023, 'Oberlin College');
Insert princeton_review_great_school_major values(13, 1,'Princeton University');
Insert princeton_review_great_school_major values(13, 1117, 'Ripon College');
Insert princeton_review_great_school_major values(13, 1043, 'Trinity College');
Insert princeton_review_great_school_major values(13, 50, 'Tulane University');
Insert princeton_review_great_school_major values(13, 23, 'University of Virginia');
Insert princeton_review_great_school_major values(13, 1064, 'Wabash College');
Insert princeton_review_great_school_major values(13, 1000, 'Williams College');
Insert princeton_review_great_school_major values(13, 3,'Yale University');

Insert princeton_review_great_school_major values(14, 87, 'American University');
Insert princeton_review_great_school_major values(14, 127, 'Arizona State University-Tempe');
Insert princeton_review_great_school_major values(14, 142, 'Auburn University');
Insert princeton_review_great_school_major values(14, 168, 'Ball State University');
Insert princeton_review_great_school_major values(14, 57, 'Boston University');
Insert princeton_review_great_school_major values(14, 185, 'Bowling Green State University');
Insert princeton_review_great_school_major values(14, 1007, 'Carleton College');
Insert princeton_review_great_school_major values(14, 8,'Duke University');
Insert princeton_review_great_school_major values(14, 2009, 'Emerson College');
Insert princeton_review_great_school_major values(14, 54, 'George Washington University');
Insert princeton_review_great_school_major values(14, 5018, 'Hampton University');
Insert princeton_review_great_school_major values(14, 102, 'Howard University');
Insert princeton_review_great_school_major values(14, 75,'Indiana University-Bloomington');
Insert princeton_review_great_school_major values(14, 86, 'Iowa State University');
Insert princeton_review_great_school_major values(14, 2008, 'Ithaca College');
Insert princeton_review_great_school_major values(14, 123, 'Kansas State University');
Insert princeton_review_great_school_major values(14, 5012, 'Loyola University New Orleans');
Insert princeton_review_great_school_major values(14, 72, 'Michigan State University');
Insert princeton_review_great_school_major values(14, 34, 'New York University');
Insert princeton_review_great_school_major values(14, 15, 'Northwestern University');
Insert princeton_review_great_school_major values(14, 116, 'Ohio University');
Insert princeton_review_great_school_major values(14, 48, 'Pennsylvania State University-University Park');
Insert princeton_review_great_school_major values(14, 2023, 'St. Bonaventure University');
Insert princeton_review_great_school_major values(14, 99, 'SUNY-Stony Brook');
Insert princeton_review_great_school_major values(14, 51, 'Syracuse University');
Insert princeton_review_great_school_major values(14, 129, 'Temple University');
Insert princeton_review_great_school_major values(14, 93, 'University of Alabama');
Insert princeton_review_great_school_major values(14, 105,'University of Arizona');
Insert princeton_review_great_school_major values(14, 49,'University of Florida');
Insert princeton_review_great_school_major values(14, 60, 'University of Georgia');
Insert princeton_review_great_school_major values(14, 85, 'University of Kansas');
Insert princeton_review_great_school_major values(14, 120, 'University of Kentucky');
Insert princeton_review_great_school_major values(14, 171, 'University of Idaho');
Insert princeton_review_great_school_major values(14, 40, 'University of Illinois-Urbana-Champaign');
Insert princeton_review_great_school_major values(14, 64, 'University of Iowa');
Insert princeton_review_great_school_major values(14, 56, 'University of Maryland-College Park');
Insert princeton_review_great_school_major values(14, 74, 'University of Minnesota-Twin Cities');
Insert princeton_review_great_school_major values(14, 146, 'University of Mississippi');
Insert princeton_review_great_school_major values(14, 92, 'University of Missouri-Columbia');
Insert princeton_review_great_school_major values(14, 251, 'University of Montana');
Insert princeton_review_great_school_major values(14, 95, 'University of Nebraska-Lincon');
Insert princeton_review_great_school_major values(14, 28, 'University of North Carolina-Chapel Hill');
Insert princeton_review_great_school_major values(14, 110, 'University of Oklahoma');
Insert princeton_review_great_school_major values(14, 114, 'University of Oregon');
Insert princeton_review_great_school_major values(14, 27, 'University of Southern California');
Insert princeton_review_great_school_major values(14, 45, 'University of Texas-Austin');
Insert princeton_review_great_school_major values(14, 38, 'University of Wisconsin-Madison');
Insert princeton_review_great_school_major values(14, 119, 'Washington State University');


Insert princeton_review_great_school_major values(15, 10000, 'Babson College');
Insert princeton_review_great_school_major values(15, 76, 'Baylor University');
Insert princeton_review_great_school_major values(15, 2002, 'Bentley University');
Insert princeton_review_great_school_major values(15, 130, 'Duquesne University');
Insert princeton_review_great_school_major values(15, 2005, 'Fairfield University');
Insert princeton_review_great_school_major values(15, 140, 'Hofstra University');
Insert princeton_review_great_school_major values(15, 75, 'Indiana University-Bloomington');
Insert princeton_review_great_school_major values(15, 86, 'Iowa State University');
Insert princeton_review_great_school_major values(15, 5007, 'James Madison University');
Insert princeton_review_great_school_major values(15, 70, 'Miami University-Oxford');
Insert princeton_review_great_school_major values(15, 2001, 'Providence College');
Insert princeton_review_great_school_major values(15, 3005, 'Seattle University');
Insert princeton_review_great_school_major values(15, 1113, 'Siena College');
Insert princeton_review_great_school_major values(15, 51, 'Syracuse University');
Insert princeton_review_great_school_major values(15, 62, 'Texas A&M University-College Station');
Insert princeton_review_great_school_major values(15, 170, 'University of Central Florida');
Insert princeton_review_great_school_major values(15, 26, 'University of Michigan-Ann Arbor');
Insert princeton_review_great_school_major values(15, 146, 'University of Mississippi');
Insert princeton_review_great_school_major values(15, 5, 'University of Pennsylvania');
Insert princeton_review_great_school_major values(15, 158, 'University of South Florida');
Insert princeton_review_great_school_major values(15, 45, 'University of Texas-Austin');


Insert princeton_review_great_school_major values(16, 1066, 'Agnes Scott College');
Insert princeton_review_great_school_major values(16, 1003, 'Bowdoin College');
Insert princeton_review_great_school_major values(16, 2010, 'Bryant University');
Insert princeton_review_great_school_major values(16, 1025, 'Bryn Mawr College');
Insert princeton_review_great_school_major values(16, 6, 'California Institute of Technology');
Insert princeton_review_great_school_major values(16, 1007, 'Carleton College');
Insert princeton_review_great_school_major values(16, 1032, 'College of the Holy Cross');
Insert princeton_review_great_school_major values(16, 1168, 'College of Idaho');
Insert princeton_review_great_school_major values(16, 1020, 'Grinnell College');
Insert princeton_review_great_school_major values(16, 1013, 'Hamilton College');
Insert princeton_review_great_school_major values(16, 6014, 'Champlain College');
Insert princeton_review_great_school_major values(16, 2,'Harvard University');
Insert princeton_review_great_school_major values(16, 1014, 'Harvey Mudd College');
Insert princeton_review_great_school_major values(16, 1011, 'Haverford College');
Insert princeton_review_great_school_major values(16, 1022, 'Macalester College');
Insert princeton_review_great_school_major values(16, 7,'Massachusetts Institute of Technology');
Insert princeton_review_great_school_major values(16, 1160, 'Randolph College');
Insert princeton_review_great_school_major values(16, 1095, 'Reed College');
Insert princeton_review_great_school_major values(16, 17, 'Rice University');
Insert princeton_review_great_school_major values(16, 1059, 'St. Lawrence University');
Insert princeton_review_great_school_major values(16, 1053, 'St. Olaf College');
Insert princeton_review_great_school_major values(16, 137, 'SUNY-Albany');
Insert princeton_review_great_school_major values(16, 6000, 'United States Coast Guard Academy');
Insert princeton_review_great_school_major values(16, 10, 'University of Chicago');
Insert princeton_review_great_school_major values(16, 35, 'University of Rochester');
Insert princeton_review_great_school_major values(16, 1064, 'Wabash College');

Insert princeton_review_great_school_major values(17, 142, 'Auburn University');
Insert princeton_review_great_school_major values(17, 4003, 'Bradley University');
Insert princeton_review_great_school_major values(17, 6, 'California Institute of Technology');
Insert princeton_review_great_school_major values(17, 124, 'Clarkson University');
Insert princeton_review_great_school_major values(17, 125, 'Colorado State University');
Insert princeton_review_great_school_major values(17, 6001, 'Cooper Union');
Insert princeton_review_great_school_major values(17, 108, 'Drexel University');
Insert princeton_review_great_school_major values(17, 10001, 'Franklin W. Olin College of Engineering');
Insert princeton_review_great_school_major values(17, 36,'Georgia Institute of Technology');
Insert princeton_review_great_school_major values(17, 1133, 'Grove City College');
Insert princeton_review_great_school_major values(17, 1014, 'Harvey Mudd College');
Insert princeton_review_great_school_major values(17, 100, 'Illinois Institute of Technology');
Insert princeton_review_great_school_major values(17, 86, 'Iowa State University');
Insert princeton_review_great_school_major values(17, 31, 'Lehigh University');
Insert princeton_review_great_school_major values(17, 7, 'Massachusetts Institute of Technology');
Insert princeton_review_great_school_major values(17, 122, 'New Jersey Institute of Technology');
Insert princeton_review_great_school_major values(17, 89,'North Carolina State University-Raleigh');
Insert princeton_review_great_school_major values(17, 66, 'Purdue University-West Lafayette');
Insert princeton_review_great_school_major values(17, 2006, 'Rochester Institute of Technology');
Insert princeton_review_great_school_major values(17, 10003, 'Rose-Hulman Institute of Technology');
Insert princeton_review_great_school_major values(17, 9, 'Stanford University');
Insert princeton_review_great_school_major values(17, 118, 'University at Buffalo-SUNY');


Insert princeton_review_great_school_major values(18, 3091, 'Angelo State University');
Insert princeton_review_great_school_major values(18, 76, 'Baylor University');
Insert princeton_review_great_school_major values(18, 5013, 'Bellarmine University');
Insert princeton_review_great_school_major values(18, 1120, 'Calvin College');
Insert princeton_review_great_school_major values(18, 121, 'Cathodtc University of America');
Insert princeton_review_great_school_major values(18, 108, 'Drexel University');
Insert princeton_review_great_school_major values(18, 130, 'Duquesne University');
Insert princeton_review_great_school_major values(18, 2005, 'Fairfield University');
Insert princeton_review_great_school_major values(18, 9003, 'Florida Southern College');
Insert princeton_review_great_school_major values(18, 217, 'Indiana University of Pennsylvania');
Insert princeton_review_great_school_major values(18, 111, 'Loyola University of Chicago');
Insert princeton_review_great_school_major values(18, 7005, 'Montana Tech of the University of Montana');
Insert princeton_review_great_school_major values(18, 8002, 'Ohio Northern University');
Insert princeton_review_great_school_major values(18,  83, 'Saint Louis University');
Insert princeton_review_great_school_major values(18, 107,'Texas Christian University');
Insert princeton_review_great_school_major values(18, 93, 'University of Alabama');
Insert princeton_review_great_school_major values(18, 5, 'University of Pennsylvania');
Insert princeton_review_great_school_major values(18, 174, 'University of Wyoming');
Insert princeton_review_great_school_major values(18, 4004, 'Valparaiso University');
Insert princeton_review_great_school_major values(18, 2000, 'Villanova University');
Insert princeton_review_great_school_major values(18, 119, 'Washington State University');
Insert princeton_review_great_school_major values(18, 4005, 'Xavier University');

Insert princeton_review_great_school_major values(19, 87, 'American University');
Insert princeton_review_great_school_major values(19, 1001, 'Amherst College');
Insert princeton_review_great_school_major values(19, 1044, 'Bard College');
Insert princeton_review_great_school_major values(19, 1024, 'Bates College');
Insert princeton_review_great_school_major values(19, 1003, 'Bowdoin College');
Insert princeton_review_great_school_major values(19, 79, 'Brigham Young University-Provo');
Insert princeton_review_great_school_major values(19, 1025, 'Bryn Mawr College');
Insert princeton_review_great_school_major values(19, 1007, 'Carleton College');
Insert princeton_review_great_school_major values(19, 1008, 'Claremont McKenna College');
Insert princeton_review_great_school_major values(19, 1032, 'College of the Holy Cross');
Insert princeton_review_great_school_major values(19, 4,'Columbia University');
Insert princeton_review_great_school_major values(19, 1009, 'Davidson College');
Insert princeton_review_great_school_major values(19, 1039, 'Dickinson College');
Insert princeton_review_great_school_major values(19, 1111, 'Drew University');
Insert princeton_review_great_school_major values(19, 1051, 'Furman University');
Insert princeton_review_great_school_major values(19, 139, 'George Mason University');
Insert princeton_review_great_school_major values(19, 54, 'George Washington University');
Insert princeton_review_great_school_major values(19, 24, 'Georgetown University');
Insert princeton_review_great_school_major values(19, 1048, 'Gettysburg College');
Insert princeton_review_great_school_major values(19, 3003, 'Gonzaga University');
Insert princeton_review_great_school_major values(19, 2,'Harvard University');
Insert princeton_review_great_school_major values(19, 1027, 'Kenyon College');
Insert princeton_review_great_school_major values(19, 1022, 'Macalester College');
Insert princeton_review_great_school_major values(19, 1,'Princeton University');
Insert princeton_review_great_school_major values(19, 9,'Stanford University');
Insert princeton_review_great_school_major values(19, 1002, 'Swarthmore College');
Insert princeton_review_great_school_major values(19, 51, 'Syracuse University');
Insert princeton_review_great_school_major values(19, 105,'University of Arizona');
Insert princeton_review_great_school_major values(19, 21, 'University of California-Berkeley');
Insert princeton_review_great_school_major values(19, 25, 'University of California-Los Angeles');
Insert princeton_review_great_school_major values(19, 42, 'University of Washington');
Insert princeton_review_great_school_major values(19, 1012, 'Vassar College');
Insert princeton_review_great_school_major values(19, 3,'Yale University');


Insert princeton_review_great_school_major values(20, 1099, 'Albion College');
Insert princeton_review_great_school_major values(20, 1024, 'Bates College');
Insert princeton_review_great_school_major values(20, 22, 'Carnegie Mellon University');
Insert princeton_review_great_school_major values(20, 5014, 'Christopher Newport University');
Insert princeton_review_great_school_major values(20, 8013, 'Clarke University');
Insert princeton_review_great_school_major values(20, 125, 'Colorado State University');
Insert princeton_review_great_school_major values(20, 4,'Columbia University');
Insert princeton_review_great_school_major values(20, 13, 'Cornell University');
Insert princeton_review_great_school_major values(20, 11, 'Dartmouth College');
Insert princeton_review_great_school_major values(20, 8,'Duke University');
Insert princeton_review_great_school_major values(20, 1048, 'Gettysburg College');
Insert princeton_review_great_school_major values(20, 2,'Harvard University');
Insert princeton_review_great_school_major values(20, 5007, 'James Madison University');
Insert princeton_review_great_school_major values(20, 7025, 'Lewis-Clark State College');
Insert princeton_review_great_school_major values(20, 111, 'Loyola University of Chicago');
Insert princeton_review_great_school_major values(20, 34, 'New York University');
Insert princeton_review_great_school_major values(20, 1035, 'Pitzer College');
Insert princeton_review_great_school_major values(20, 232, 'Portland State University');
Insert princeton_review_great_school_major values(20, 1,'Princeton University');
Insert princeton_review_great_school_major values(20, 1144, 'Roanoke College');
Insert princeton_review_great_school_major values(20, 1015, 'Smith College');
Insert princeton_review_great_school_major values(20, 9, 'Stanford University');
Insert princeton_review_great_school_major values(20, 43, 'University of California-Davis');
Insert princeton_review_great_school_major values(20, 25, 'University of California-Los Angeles');
Insert princeton_review_great_school_major values(20, 103, 'University of California-Riverside');
Insert princeton_review_great_school_major values(20, 46, 'University of California-Santa Barbara');
Insert princeton_review_great_school_major values(20, 81, 'University of California-Santa Cruz');
Insert princeton_review_great_school_major values(20, 189, 'University of Houston');
Insert princeton_review_great_school_major values(20, 26, 'University of Michigan-Ann Arbor');
Insert princeton_review_great_school_major values(20, 27, 'University of Southern California');
Insert princeton_review_great_school_major values(20, 45, 'University of Texas-Austin');
Insert princeton_review_great_school_major values(20, 132, 'University of Utah');
Insert princeton_review_great_school_major values(20, 12, 'Washington University in St. Louis');
Insert princeton_review_great_school_major values(20, 3,'Yale University');


select s.name, m.name from princeton_review_great_school_major g, school s, princeton_review_popular_major m 
where School_Id=s.id and major_Id=m.id and s.name='Yale University';

select s.name, m.name from princeton_review_great_school_major g, school s, princeton_review_popular_major m 
where School_Id=s.id and major_Id=m.id and m.name='Accounting';

