DROP TABLE IF EXISTS school_rank_in_program;
CREATE TABLE school_rank_in_program
(
  School_Id INT NOT NULL,
  Rank INT,
  School_Name VARCHAR(80),
  Speciality VARCHAR(80),
  Primary Key (School_Id, Speciality),
  FOREIGN KEY (School_Id) REFERENCES school (Id)

);


Insert school_rank_in_program values(7,1,'Massachusetts Institute of Technology','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(36,2,'Georgia Institute of Technology','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(26,3,'University of Michigan-Ann Arbor','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(66,4,'Purdue University-West Lafayette','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(6,5,'California Institute of Technology','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(4,6,'Stanford University','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(1,7,'Princeton University','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(40,7,'University of Illinois-Urbana-Champaign','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(56,9,'University of Maryland-College Park','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(80,10,'University of Colorado-Boulder','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(45,10,'University of Texas-Austin','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(62,12,'Texas A&M University-College Station','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(21,12,'University of California-Berkeley','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(48,14,'Pennsylvania State University-University Park','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(42,15,'University of Washington','Aerospace-Aeronautical-Astronautical_Doctorate');
Insert school_rank_in_program values(71,15,'Virginia Tech','Aerospace-Aeronautical-Astronautical_Doctorate');

Insert school_rank_in_program values(66,1,'Purdue University-West Lafayette','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(86,2,'Iowa State University','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(62,2,'Texas A&M University-College Station','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(40,2,'University of Illinois-Urbana-Champaign','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(43,5,'University of California-Davis','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(49,6,'University of Florida','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(71,6,'Virginia Tech','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(13,8,'Cornell University','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(95,9,'University of Nebraska-Lincoln','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(89,10,'North Carolina State University-Raleigh','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(58,10,'Ohio State University-Columbus','Biological-Agricultural_Doctorate');
Insert school_rank_in_program values(72,12,'Michigan State University','Biological-Agricultural_Doctorate');


Insert school_rank_in_program values(16,1,'Johns Hopkins University','Biomedical_Doctorate');
Insert school_rank_in_program values(8,2,'Duke University','Biomedical_Doctorate');
Insert school_rank_in_program values(36,3,'Georgia Institute of Technology','Biomedical_Doctorate');
Insert school_rank_in_program values(7,4,'Massachusetts Institute of Technology','Biomedical_Doctorate');
Insert school_rank_in_program values(17,4,'Rice University','Biomedical_Doctorate');
Insert school_rank_in_program values(4,4,'Stanford University','Biomedical_Doctorate');
Insert school_rank_in_program values(39,7,'University of California-San Diego','Biomedical_Doctorate');
Insert school_rank_in_program values(5,8,'University of Pennsylvania','Biomedical_Doctorate');
Insert school_rank_in_program values(21,9,'University of California-Berkeley','Biomedical_Doctorate');
Insert school_rank_in_program values(26,10,'University of Michigan-Ann Arbor','Biomedical_Doctorate');
Insert school_rank_in_program values(42,11,'University of Washington','Biomedical_Doctorate');
Insert school_rank_in_program values(57,12,'Boston University','Biomedical_Doctorate');
Insert school_rank_in_program values(41,12,'Case Western Reserve University','Biomedical_Doctorate');
Insert school_rank_in_program values(15,12,'Northwestern University','Biomedical_Doctorate');
Insert school_rank_in_program values(19,15,'Vanderbilt University','Biomedical_Doctorate');
Insert school_rank_in_program values(45,16,'University of Texas-Austin','Biomedical_Doctorate');
Insert school_rank_in_program values(38,17,'University of Wisconsin-Madison','Biomedical_Doctorate');
Insert school_rank_in_program values(23,18,'University of Virginia','Biomedical_Doctorate');
Insert school_rank_in_program values(12,18,'Washington University in St. Louis','Biomedical_Doctorate');
Insert school_rank_in_program values(6,20,'California Institute of Technology','Biomedical_Doctorate');
Insert school_rank_in_program values(40,21,'University of Illinois-Urbana-Champaign','Biomedical_Doctorate');
Insert school_rank_in_program values(61,21,'University of Pittsburgh','Biomedical_Doctorate');

Insert school_rank_in_program values(7,1,'Massachusetts Institute of Technology','Chemical_Doctorate');
Insert school_rank_in_program values(21,2,'University of California-Berkeley','Chemical_Doctorate');
Insert school_rank_in_program values(4,3,'Stanford University','Chemical_Doctorate');
Insert school_rank_in_program values(45,4,'University of Texas-Austin','Chemical_Doctorate');
Insert school_rank_in_program values(74,5,'University of Minnesota-Twin Cities','Chemical_Doctorate');
Insert school_rank_in_program values(36,6,'Georgia Institute of Technology','Chemical_Doctorate');
Insert school_rank_in_program values(38,6,'University of Wisconsin-Madison','Chemical_Doctorate');
Insert school_rank_in_program values(6,8,'California Institute of Technology','Chemical_Doctorate');
Insert school_rank_in_program values(1,9,'Princeton University','Chemical_Doctorate');
Insert school_rank_in_program values(73,10,'University of Delaware','Chemical_Doctorate');
Insert school_rank_in_program values(26,11,'University of Michigan-Ann Arbor','Chemical_Doctorate');
Insert school_rank_in_program values(66,12,'Purdue University-West Lafayette','Chemical_Doctorate');
Insert school_rank_in_program values(40,13,'University of Illinois-Urbana-Champaign','Chemical_Doctorate');
Insert school_rank_in_program values(13,14,'Cornell University','Chemical_Doctorate');
Insert school_rank_in_program values(15,14,'Northwestern University','Chemical_Doctorate');
Insert school_rank_in_program values(48,16,'Pennsylvania State University-University Park','Chemical_Doctorate');
Insert school_rank_in_program values(22,17,'Carnegie Mellon University','Chemical_Doctorate');
Insert school_rank_in_program values(46,17,'University of California-Santa Barbara','Chemical_Doctorate');
Insert school_rank_in_program values(89,19,'North Carolina State University-Raleigh','Chemical_Doctorate');
Insert school_rank_in_program values(80,20,'University of Colorado-Boulder','Chemical_Doctorate');
Insert school_rank_in_program values(62,21,'Texas A&M University-College Station','Chemical_Doctorate');


Insert school_rank_in_program values(21,1,'University of California-Berkeley','Civil_Doctorate');
Insert school_rank_in_program values(40,2,'University of Illinois-Urbana-Champaign','Civil_Doctorate');
Insert school_rank_in_program values(36,3,'Georgia Institute of Technology','Civil_Doctorate');
Insert school_rank_in_program values(4,4,'Stanford University','Civil_Doctorate');
Insert school_rank_in_program values(66,5,'Purdue University-West Lafayette','Civil_Doctorate');
Insert school_rank_in_program values(45,6,'University of Texas-Austin','Civil_Doctorate');
Insert school_rank_in_program values(7,7,'Massachusetts Institute of Technology','Civil_Doctorate');
Insert school_rank_in_program values(26,8,'University of Michigan-Ann Arbor','Civil_Doctorate');
Insert school_rank_in_program values(13,9,'Cornell University','Civil_Doctorate');
Insert school_rank_in_program values(71,9,'Virginia Tech','Civil_Doctorate');
Insert school_rank_in_program values(62,11,'Texas A&M University-College Station','Civil_Doctorate');
Insert school_rank_in_program values(38,12,'University of Wisconsin-Madison','Civil_Doctorate');
Insert school_rank_in_program values(22,13,'Carnegie Mellon University','Civil_Doctorate');
Insert school_rank_in_program values(15,14,'Northwestern University','Civil_Doctorate');
Insert school_rank_in_program values(6,15,'California Institute of Technology','Civil_Doctorate');
Insert school_rank_in_program values(48,15,'Pennsylvania State University-University Park','Civil_Doctorate');
Insert school_rank_in_program values(1,17,'Princeton University','Civil_Doctorate');
Insert school_rank_in_program values(80,17,'University of Colorado-Boulder','Civil_Doctorate');

Insert school_rank_in_program values(7,1,'Massachusetts Institute of Technology','Computer_Doctorate');
Insert school_rank_in_program values(4,2,'Stanford University','Computer_Doctorate');
Insert school_rank_in_program values(22,3,'Carnegie Mellon University','Computer_Doctorate');
Insert school_rank_in_program values(21,4,'University of California-Berkeley','Computer_Doctorate');
Insert school_rank_in_program values(40,5,'University of Illinois-Urbana-Champaign','Computer_Doctorate');
Insert school_rank_in_program values(36,6,'Georgia Institute of Technology','Computer_Doctorate');
Insert school_rank_in_program values(26,7,'University of Michigan-Ann Arbor','Computer_Doctorate');
Insert school_rank_in_program values(45,8,'University of Texas-Austin','Computer_Doctorate');
Insert school_rank_in_program values(6,9,'California Institute of Technology','Computer_Doctorate');
Insert school_rank_in_program values(13,10,'Cornell University','Computer_Doctorate');
Insert school_rank_in_program values(42,11,'University of Washington','Computer_Doctorate');
Insert school_rank_in_program values(1,12,'Princeton University','Computer_Doctorate');
Insert school_rank_in_program values(66,13,'Purdue University-West Lafayette','Computer_Doctorate');
Insert school_rank_in_program values(38,13,'University of Wisconsin-Madison','Computer_Doctorate');
Insert school_rank_in_program values(27,15,'University of Southern California','Computer_Doctorate');


Insert school_rank_in_program values(7,1,'Massachusetts Institute of Technology','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(4,2,'Stanford University','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(21,3,'University of California-Berkeley','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(36,4,'Georgia Institute of Technology','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(40,5,'University of Illinois-Urbana-Champaign','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(26,6,'University of Michigan-Ann Arbor','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(6,7,'California Institute of Technology','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(45,8,'University of Texas-Austin','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(66,9,'Purdue University-West Lafayette','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(13,10,'Cornell University','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(22,11,'Carnegie Mellon University','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(1,12,'Princeton University','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(25,13,'University of California-Los Angeles','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(38,14,'University of Wisconsin-Madison','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(71,14,'Virginia Tech','Electrical-Electronic-Communications_Doctorate');
Insert school_rank_in_program values(39,14,'University of California-San Diego','Electrical-Electronic-Communications_Doctorate');

Insert school_rank_in_program values(4,1,'Stanford University','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(21,2,'University of California-Berkeley','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(26,3,'University of Michigan-Ann Arbor','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(40,4,'University of Illinois-Urbana-Champaign','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(45,5,'University of Texas-Austin','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(36,6,'Georgia Institute of Technology','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(16,7,'Johns Hopkins University','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(7,8,'Massachusetts Institute of Technology','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(22,9,'Carnegie Mellon University','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(13,10,'Cornell University','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(71,11,'Virginia Tech','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(6,12,'California Institute of Technology','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(66,13,'Purdue University-West Lafayette','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(80,13,'University of Colorado-Boulder','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(89,15,'North Carolina State University-Raleigh','Environmental-Environmental Health_Doctorate');
Insert school_rank_in_program values(49,15,'University of Florida','Environmental-Environmental Health_Doctorate');


Insert school_rank_in_program values(36,1,'Georgia Institute of Technology','Industrial-Manufacturingh_Doctorate');
Insert school_rank_in_program values(26,2,'University of Michigan-Ann Arbor','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(66,3,'Purdue University-West Lafayette','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(21,3,'University of California-Berkeley','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(15,5,'Northwestern University','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(4,5,'Stanford University','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(71,5,'Virginia Tech','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(48,8,'Pennsylvania State University-University Park','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(38,9,'University of Wisconsin-Madison','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(13,10,'Cornell University','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(62,11,'Texas A&M University-College Station','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(7,12,'Massachusetts Institute of Technology','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(89,13,'North Carolina State University-Raleigh','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(58,14,'Ohio State University-Columbus','Industrial-Manufacturing_Doctorate');
Insert school_rank_in_program values(9,15,'Columbia Universityh','Industrial-Manufacturing_Doctorate');

Insert school_rank_in_program values(7,1,'Massachusetts Institute of Technology','Materials_Doctorate');
Insert school_rank_in_program values(40,2,'University of Illinois-Urbana-Champaign','Materials_Doctorate');
Insert school_rank_in_program values(21,3,'University of California-Berkeley','Materials_Doctorate');
Insert school_rank_in_program values(15,4,'Northwestern University','Materials_Doctorate');
Insert school_rank_in_program values(26,5,'University of Michigan-Ann Arbor','Materials_Doctorate');
Insert school_rank_in_program values(4,6,'Stanford University','Materials_Doctorate');
Insert school_rank_in_program values(36,7,'Georgia Institute of Technology','Materials_Doctorate');
Insert school_rank_in_program values(13,8,'Cornell University','Materials_Doctorate');
Insert school_rank_in_program values(48,9,'Pennsylvania State University-University Park','Materials_Doctorate');
Insert school_rank_in_program values(46,10,'University of California-Santa Barbara','Materials_Doctorate');
Insert school_rank_in_program values(22,11,'Carnegie Mellon University','Materials_Doctorate');
Insert school_rank_in_program values(6,12,'California Institute of Technology','Materials_Doctorate');
Insert school_rank_in_program values(49,13,'University of Florida','Materials_Doctorate');
Insert school_rank_in_program values(66,14,'Purdue University-West Lafayette','Materials_Doctorate');
Insert school_rank_in_program values(5,14,'University of Pennsylvania','Materials_Doctorate');
Insert school_rank_in_program values(58,16,'Ohio State University-Columbus','Materials_Doctorate');
Insert school_rank_in_program values(78,17,'Colorado School of Mines','Materials_Doctorate');
Insert school_rank_in_program values(17,17,'Rice University','Materials_Doctorate');
Insert school_rank_in_program values(71,17,'Virginia Tech','Materials_Doctorate');


Insert school_rank_in_program values(7,1,'Massachusetts Institute of Technology','Mechanical_Doctorate');
Insert school_rank_in_program values(36,2,'Georgia Institute of Technology','Mechanical_Doctorate');
Insert school_rank_in_program values(21,3,'University of California-Berkeley','Mechanical_Doctorate');
Insert school_rank_in_program values(4,4,'Stanford University','Mechanical_Doctorate');
Insert school_rank_in_program values(26,5,'University of Michigan-Ann Arbor','Mechanical_Doctorate');
Insert school_rank_in_program values(66,6,'Purdue University-West Lafayette','Mechanical_Doctorate');
Insert school_rank_in_program values(40,6,'University of Illinois-Urbana-Champaign','Mechanical_Doctorate');
Insert school_rank_in_program values(13,8,'Cornell University','Mechanical_Doctorate');
Insert school_rank_in_program values(6,9,'California Institute of Technology','Mechanical_Doctorate');
Insert school_rank_in_program values(45,10,'University of Texas-Austin','Mechanical_Doctorate');
Insert school_rank_in_program values(22,11,'Carnegie Mellon University','Mechanical_Doctorate');
Insert school_rank_in_program values(1,12,'Princeton University','Mechanical_Doctorate');
Insert school_rank_in_program values(15,13,'Northwestern University','Mechanical_Doctorate');
Insert school_rank_in_program values(38,14,'University of Wisconsin-Madison','Mechanical_Doctorate');
Insert school_rank_in_program values(62,15,'Texas A&M University-College Station','Mechanical_Doctorate');
Insert school_rank_in_program values(71,15,'Virginia Tech','Mechanical_Doctorate');
Insert school_rank_in_program values(48,17,'Pennsylvania State University-University Park','Mechanical_Doctorate');
Insert school_rank_in_program values(5,17,'University of Pennsylvania','Mechanical_Doctorate');
Insert school_rank_in_program values(56,19,'University of Maryland-College Park','Mechanical_Doctorate');
  

Insert school_rank_in_program values(5009,1,'Embry-Riddle Aeronautical University','Aerospace-Aeronautical-Astronautical_No_Doctorate');
Insert school_rank_in_program values(1030,2,'United States Air Force Academy','Aerospace-Aeronautical-Astronautical_No_Doctorate');
Insert school_rank_in_program values(5133,1,'Embry-Riddle Aeronautical University-Prescott','Aerospace-Aeronautical-Astronautical_No_Doctorate');

Insert school_rank_in_program values(10003,1,'Rose-Hulman Institute of Technology','Biomedical_No_Doctorate');

Insert school_rank_in_program values(10003,1,'Rose-Hulman Institute of Technology','Civil_No_Doctorate');
Insert school_rank_in_program values(1021,2,'United States Military Academy','Civil_No_Doctorate');
Insert school_rank_in_program values(3009,3,'California Polytechnic State University-San Luis Obispo','Civil_No_Doctorate');
Insert school_rank_in_program values(1031,4,'Bucknell University','Civil_No_Doctorate');
Insert school_rank_in_program values(4056,5,'Lawrence Technological University','Civil_No_Doctorate');


Insert school_rank_in_program values(10003,1,'Rose-Hulman Institute of Technology','Computer_No_Doctorate');
Insert school_rank_in_program values(1014,2,'Harvey Mudd College','Computer_No_Doctorate');
Insert school_rank_in_program values(1031,3,'Bucknell University','Computer_No_Doctorate');
Insert school_rank_in_program values(6001,4,'Cooper Union','Computer_No_Doctorate');
Insert school_rank_in_program values(10001,5,'Franklin W. Olin College of Engineering','Computer_No_Doctorate');

Insert school_rank_in_program values(10003,1,'Rose-Hulman Institute of Technology','Electrical-Electronic-Communications_No_Doctorate');
Insert school_rank_in_program values(1031,2,'Bucknell University','Electrical-Electronic-Communications_No_Doctorate');
Insert school_rank_in_program values(10001,2,'Franklin W. Olin College of Engineering','Electrical-Electronic-Communications_No_Doctorate');
Insert school_rank_in_program values(1014,4,'Harvey Mudd College','Electrical-Electronic-Communications_No_Doctorate');
Insert school_rank_in_program values(1030,5,'United States Air Force Academy','Electrical-Electronic-Communications_No_Doctorate');

Insert school_rank_in_program values(10003,1,'Rose-Hulman Institute of Technology','Mechanical_No_Doctorate');
Insert school_rank_in_program values(10001,2,'Franklin W. Olin College of Engineering','Mechanical_No_Doctorate');
Insert school_rank_in_program values(3009,3,'California Polytechnic State University-San Luis Obispo','Mechanical_No_Doctorate');
Insert school_rank_in_program values(1021,4,'United States Military Academy','Mechanical_No_Doctorate');
Insert school_rank_in_program values(1014,5,'Harvey Mudd College','Mechanical_No_Doctorate');
Insert school_rank_in_program values(1030,5,'United States Air Force Academy','Mechanical_No_Doctorate');
Insert school_rank_in_program values(1031,7,'Bucknell University','Mechanical_No_Doctorate');
Insert school_rank_in_program values(4024,7,'Kettering University','Mechanical_No_Doctorate');
Insert school_rank_in_program values(6001,9,'Cooper Union','Mechanical_No_Doctorate');
Insert school_rank_in_program values(1010,10,'United States Naval Academy','Mechanical_No_Doctorate');

Insert school_rank_in_program values(45,1,'University of Texas-Austin','Accounting');
Insert school_rank_in_program values(40,2,'University of Illinois-Urbana-Champaign','Accounting');
Insert school_rank_in_program values(79,3,'Brigham Young University-Provo','Accounting');
Insert school_rank_in_program values(20,4,'University of Notre Dame','Accounting');
Insert school_rank_in_program values(5,4,'University of Pennsylvania','Accounting');
Insert school_rank_in_program values(27,6,'University of Southern California','Accounting');
Insert school_rank_in_program values(75,7,'Indiana University-Bloomington','Accounting');
Insert school_rank_in_program values(26,8,'University of Michigan-Ann Arbor','Accounting');
Insert school_rank_in_program values(34,9,'New York University','Accounting');
Insert school_rank_in_program values(49,10,'University of Florida','Accounting');
Insert school_rank_in_program values(42,11,'University of Washington','Accounting');
Insert school_rank_in_program values(72,12,'UMichigan State University','Accounting');
Insert school_rank_in_program values(58,13,'Ohio State University-Columbus','Accounting');
Insert school_rank_in_program values(3005,13,'Seattle University','Accounting');
Insert school_rank_in_program values(21,13,'University of California-Berkeley','Accounting');
Insert school_rank_in_program values(60,13,'University of Georgia','Accounting');
Insert school_rank_in_program values(37,17,'Boston College','Accounting');
Insert school_rank_in_program values(38,17,'University of Wisconsin-Madison','Accounting');
Insert school_rank_in_program values(4000,19,'Creighton University','Accounting');
Insert school_rank_in_program values(3002,19,'Loyola Marymount University','Accounting');
Insert school_rank_in_program values(2005,21,'Fairfield University','Accounting');
Insert school_rank_in_program values(2014,21,'St. Joseph-s University','Accounting');
Insert school_rank_in_program values(28,21,'University of North Carolina-Chapel Hill','Accounting');
Insert school_rank_in_program values(23,21,'University of Virginia','Accounting');
Insert school_rank_in_program values(30,21,'Wake Forest UniversityWake Forest University','Accounting');
Insert school_rank_in_program values(2002,26,'Bentley University','Accounting');
Insert school_rank_in_program values(4006,26,'John Carroll University','Accounting');
Insert school_rank_in_program values(62,26,'Texas A&M University-College Station','Accounting');
Insert school_rank_in_program values(111,29,'Loyola University Chicago','Accounting');
Insert school_rank_in_program values(2004,29,'Loyola University Maryland','Accounting');
Insert school_rank_in_program values(13,31,'Cornell University','Accounting');
Insert school_rank_in_program values(2007,31,'University of Scranton','Accounting');
Insert school_rank_in_program values(127,33,'Arizona State University-Tempe','Accounting');
Insert school_rank_in_program values(188,33,'University of Alabama','Accounting');


Insert school_rank_in_program values(10000,1,'Babson College','Entrepreneurship');
Insert school_rank_in_program values(7,2,'Massachusetts Institute of Technology','Entrepreneurship');
Insert school_rank_in_program values(27,3,'University of Southern California','Entrepreneurship');
Insert school_rank_in_program values(21,4,'University of California—​Berkeley','Entrepreneurship');
Insert school_rank_in_program values(5,4,'University of Pennsylvania','Entrepreneurship');
Insert school_rank_in_program values(75,6,'Indiana University-Bloomington','Entrepreneurship');
Insert school_rank_in_program values(3002,7,'Loyola Marymount University','Entrepreneurship');
Insert school_rank_in_program values(83,7,'Saint Louis University','Entrepreneurship');
Insert school_rank_in_program values(105,7,'University of Arizona','Entrepreneurship');
Insert school_rank_in_program values(28,10,'University of North Carolina-Chapel Hill','Entrepreneurship');
Insert school_rank_in_program values(4005,10,'Xavier University','Entrepreneurship');
Insert school_rank_in_program values(51,12,'Syracuse University','Entrepreneurship');
Insert school_rank_in_program values(45,13,'University of Texas-Austin','Entrepreneurship');
Insert school_rank_in_program values(76,14,'Baylor University','Entrepreneurship');
Insert school_rank_in_program values(69,15,'Fordham University','Entrepreneurship');
Insert school_rank_in_program values(26,16,'University of Michigan-Ann Arbor','Entrepreneurship');
Insert school_rank_in_program values(34,17,'New York University','Entrepreneurship');
Insert school_rank_in_program values(56,17,'University of Maryland-College Park','Entrepreneurship');
Insert school_rank_in_program values(3003,19,'Gonzaga University','Entrepreneurship');
Insert school_rank_in_program values(107,20,'Texas Christian University','Entrepreneurship');
Insert school_rank_in_program values(151,21,'San Diego State University','Entrepreneurship');
Insert school_rank_in_program values(2007,22,'University of Scranton','Entrepreneurship');
Insert school_rank_in_program values(168,23,'Ball State University','Entrepreneurship');
Insert school_rank_in_program values(2002,23,'Bentley University','Entrepreneurship');
Insert school_rank_in_program values(79,23,'Brigham Young University-Provo','Entrepreneurship');
Insert school_rank_in_program values(42,23,'University of Washington','Entrepreneurship');

Insert school_rank_in_program values(5,1,'University of Pennsylvania','Finance');
Insert school_rank_in_program values(34,2,'New York University','Finance');
Insert school_rank_in_program values(26,3,'University of Michigan-Ann Arbor','Finance');
Insert school_rank_in_program values(7,4,'Massachusetts Institute of Technology','Finance');
Insert school_rank_in_program values(21,5,'University of California—​Berkeley','Finance');
Insert school_rank_in_program values(45,6,'University of Texas-Austin','Finance');
Insert school_rank_in_program values(23,7,'University of Virginia','Finance');
Insert school_rank_in_program values(22,8,'Carnegie Mellon University','Finance');
Insert school_rank_in_program values(28,9,'University of North Carolina-Chapel Hill','Finance');
Insert school_rank_in_program values(75,10,'Indiana University-Bloomington','Finance');
Insert school_rank_in_program values(3005,11,'Seattle University','Finance');
Insert school_rank_in_program values(37,12,'Boston College','Finance');
Insert school_rank_in_program values(58,13,'Ohio State University-Columbus','Finance');
Insert school_rank_in_program values(4000,14,'Creighton University','Finance');
Insert school_rank_in_program values(4005,15,'Xavier University','Finance');
Insert school_rank_in_program values(69,16,'Fordham University','Finance');
Insert school_rank_in_program values(12,16,'Washington University in St. Louis','Finance');
Insert school_rank_in_program values(13,18,'Cornell University','Finance');
Insert school_rank_in_program values(2005,18,'Fairfield University','Finance');
Insert school_rank_in_program values(20,20,'University of Notre Dame','Finance');
Insert school_rank_in_program values(84,21,'Marquette University','Finance');
Insert school_rank_in_program values(2004,22,'Loyola University Maryland','Finance');
Insert school_rank_in_program values(40,22,'University of Illinois-Urbana-Champaign','Finance');
Insert school_rank_in_program values(2007,22,'University of Scranton','Finance');
Insert school_rank_in_program values(27,22,'University of Southern California','Finance');
Insert school_rank_in_program values(38,22,'University of Wisconsin-Madison','Finance');
Insert school_rank_in_program values(2033,27,'Canisius College','Finance');
Insert school_rank_in_program values(49,27,'University of Florida','Finance');
Insert school_rank_in_program values(72,29,'Michigan State University','Finance');
Insert school_rank_in_program values(48,29,'Pennsylvania State University-University Park','Finance');

Insert school_rank_in_program values(5,1,'University of Pennsylvania','Insurance');
Insert school_rank_in_program values(60,2,'University of Georgia','Insurance');
Insert school_rank_in_program values(2014,3,'St. Joseph-s University','Insurance');
Insert school_rank_in_program values(38,4,'University of Wisconsin-Madison','Insurance');
Insert school_rank_in_program values(129,5,'Temple University','Insurance');
Insert school_rank_in_program values(215,6,'Georgia State University','Insurance');
Insert school_rank_in_program values(112,7,'Florida State University','Insurance');
Insert school_rank_in_program values(34,8,'New York University','Insurance');
Insert school_rank_in_program values(40,9,'University of Illinois-Urbana-Champaign','Insurance');
Insert school_rank_in_program values(45,10,'University of Texas-Austin','Insurance');
Insert school_rank_in_program values(113,11,'University of South Carolina','Insurance');
Insert school_rank_in_program values(149,12,'Illinois State University','Insurance');
Insert school_rank_in_program values(48,12,'Pennsylvania State University-University Park','Insurance');

Insert school_rank_in_program values(113,1,'University of South Carolina','International Business');
Insert school_rank_in_program values(34,2,'New York University','International Business');
Insert school_rank_in_program values(27,3,'University of Southern California','International Business');
Insert school_rank_in_program values(5,4,'University of Pennsylvania','International Business');
Insert school_rank_in_program values(21,5,'University of California—​Berkeley','International Business');
Insert school_rank_in_program values(213,6,'Florida International University','International Business');
Insert school_rank_in_program values(83,7,'Saint Louis University','International Business');
Insert school_rank_in_program values(26,7,'University of Michigan-Ann Arbor','International Business');
Insert school_rank_in_program values(24,9,'Georgetown University','International Business');
Insert school_rank_in_program values(151,10,'San Diego State University','International Business');
Insert school_rank_in_program values(54,11,'George Washington University','International Business');
Insert school_rank_in_program values(250,12,'University of Missouri-St. Louis','International Business');
Insert school_rank_in_program values(129,13,'Temple University','International Business');
Insert school_rank_in_program values(69,14,'Fordham University','International Business');
Insert school_rank_in_program values(97,15,'Northeastern University','International Business');
Insert school_rank_in_program values(166,16,'University of Hawaii-Manoa','International Business');
Insert school_rank_in_program values(72,17,'Michigan State University','International Business');
Insert school_rank_in_program values(42,17,'University of Washington','International Business');
Insert school_rank_in_program values(79,19,'Brigham Young University-Provo','International Business');
Insert school_rank_in_program values(119,20,'Washington State University','International Business');
Insert school_rank_in_program values(87,21,'American University','International Business');
Insert school_rank_in_program values(45,21,'University of Texas-Austin','International Business');
Insert school_rank_in_program values(23,21,'University of Virginia','International Business');
Insert school_rank_in_program values(4006,24,'John Carroll University','International Business');
Insert school_rank_in_program values(2004,24,'Loyola University Maryland','International Business');
Insert school_rank_in_program values(5012,24,'Loyola University New Orleans','International Business');
Insert school_rank_in_program values(28,24,'University of North Carolina-Chapel Hill','International Business');
Insert school_rank_in_program values(75,28,'Indiana University-Bloomington','International Business');
Insert school_rank_in_program values(2000,28,'Villanova University','International Business');
Insert school_rank_in_program values(127,30,'Arizona State University-Tempe','International Business');
Insert school_rank_in_program values(110,30,'University of Oklahoma','International Business');
Insert school_rank_in_program values(1033,30,'University of Richmond','International Business');

Insert school_rank_in_program values(26,1,'University of Michigan-Ann Arbor','Management');
Insert school_rank_in_program values(5,2,'University of Pennsylvania','Management');
Insert school_rank_in_program values(21,3,'University of California—​Berkeley','Management');
Insert school_rank_in_program values(23,4,'University of Virginia','Management');
Insert school_rank_in_program values(28,5,'University of North Carolina-Chapel Hill','Management');
Insert school_rank_in_program values(34,6,'New York University','Management');
Insert school_rank_in_program values(45,7,'University of Texas-Austin','Management');
Insert school_rank_in_program values(75,8,'Indiana University-Bloomington','Management');
Insert school_rank_in_program values(7,9,'Massachusetts Institute of Technology','Management');
Insert school_rank_in_program values(4018,10,'Rockhurst University','Management');
Insert school_rank_in_program values(4025,10,'University of Detroit Mercy','Management');
Insert school_rank_in_program values(20,12,'University of Notre Dame','Management');
Insert school_rank_in_program values(13,13,'Cornell University','Management');
Insert school_rank_in_program values(74,14,'​University of Minnesota-Twin Cities','Management');
Insert school_rank_in_program values(127,15,'Arizona State University-Tempe','Management');
Insert school_rank_in_program values(27,16,'University of Southern California','Management');
Insert school_rank_in_program values(62,17,'Texas A&M University-College Station','Management');
Insert school_rank_in_program values(41,18,'Case Western Reserve University','Management');
Insert school_rank_in_program values(56,19,'University of Maryland-College Park','Management');
Insert school_rank_in_program values(72,20,'Michigan State University','Management');
Insert school_rank_in_program values(58,20,'Ohio State University-Columbus','Management');
Insert school_rank_in_program values(48,20,'Pennsylvania State University-University Park','Management');
Insert school_rank_in_program values(40,20,'University of Illinois-Urbana-Champaign','Management');
Insert school_rank_in_program values(38,20,'University of Wisconsin-Madison','Management');
Insert school_rank_in_program values(18,25,'Emory University','Management');
Insert school_rank_in_program values(52,25,'University of Washington','Management');

Insert school_rank_in_program values(7,1,'Massachusetts Institute of Technology','Management Information Systems');
Insert school_rank_in_program values(22,2,'Carnegie Mellon University','Management Information Systems');
Insert school_rank_in_program values(74,3,'University of Minnesota-Twin Cities','Management Information Systems');
Insert school_rank_in_program values(105,4,'University of Arizona','Management Information Systems');
Insert school_rank_in_program values(45,5,'University of Texas-Austin','Management Information Systems');
Insert school_rank_in_program values(5,6,'University of Pennsylvania','Management Information Systems');
Insert school_rank_in_program values(36,7,'Georgia Institute of Technology','Management Information Systems');
Insert school_rank_in_program values(75,8,'Indiana University-Bloomington','Management Information Systems');
Insert school_rank_in_program values(56,9,'University of Maryland-College Park','Management Information Systems');
Insert school_rank_in_program values(34,10,'New York University','Management Information Systems');
Insert school_rank_in_program values(215,11,'Georgia State University','Management Information Systems');
Insert school_rank_in_program values(4018,12,'Rockhurst University','Management Information Systems');
Insert school_rank_in_program values(26,13,'University of Michigan-Ann Arbor','Management Information Systems');
Insert school_rank_in_program values(129,14,'Temple University','Management Information Systems');
Insert school_rank_in_program values(111,15,'Loyola University Chicago','Management Information Systems');
Insert school_rank_in_program values(21,15,'University of California—​Berkeley','Management Information Systems');
Insert school_rank_in_program values(60,15,'University of Georgia','Management Information Systems');
Insert school_rank_in_program values(127,18,'Arizona State University-Tempe','Management Information Systems');
Insert school_rank_in_program values(2002,19,'Bentley University','Management Information Systems');
Insert school_rank_in_program values(66,19,'Purdue University-West Lafayette','Management Information Systems');

Insert school_rank_in_program values(5,1,'University of Pennsylvania','Marketing');
Insert school_rank_in_program values(26,2,'University of Michigan-Ann Arbor','Marketing');
Insert school_rank_in_program values(34,3,'New York University','Marketing');
Insert school_rank_in_program values(21,4,'University of California—​Berkeley','Marketing');
Insert school_rank_in_program values(45,5,'University of Texas-Austin','Marketing');
Insert school_rank_in_program values(28,6,'University of North Carolina-Chapel Hill','Marketing');
Insert school_rank_in_program values(75,7,'Indiana University-Bloomington','Marketing');
Insert school_rank_in_program values(23,8,'University of Virginia','Marketing');
Insert school_rank_in_program values(38,9,'University of Wisconsin-Madison','Marketing');
Insert school_rank_in_program values(2014,10,'St. Joseph-s University','Marketing');
Insert school_rank_in_program values(27,11,'University of Southern California','Marketing');
Insert school_rank_in_program values(74,12,'University of Minnesota-Twin Cities','Marketing');
Insert school_rank_in_program values(2005,13,'Fairfield University','Marketing');
Insert school_rank_in_program values(3002,14,'Loyola Marymount University','Marketing');
Insert school_rank_in_program values(58,15,'Ohio State University-Columbus','Marketing');
Insert school_rank_in_program values(40,16,'University of Illinois-Urbana-Champaign','Marketing');
Insert school_rank_in_program values(20,16,'University of Notre Dame','Marketing');
Insert school_rank_in_program values(13,18,'Cornell University','Marketing');
Insert school_rank_in_program values(69,18,'Fordham University','Marketing');
Insert school_rank_in_program values(2004,18,'Loyola University Maryland','Marketing');
Insert school_rank_in_program values(18,21,'Emory University','Marketing');
Insert school_rank_in_program values(3003,21,'Gonzaga University','Marketing');
Insert school_rank_in_program values(111,21,'Loyola University Chicago','Marketing');
Insert school_rank_in_program values(7,21,'Massachusetts Institute of Technology','Marketing');
Insert school_rank_in_program values(48,21,'Pennsylvania State University-University Park','Marketing');
Insert school_rank_in_program values(12,21,'Washington University in St. Louis','Marketing');
Insert school_rank_in_program values(49,27,'University of Florida','Marketing');

Insert school_rank_in_program values(7,1,'Massachusetts Institute of Technology','Production-Operations Management');
Insert school_rank_in_program values(22,2,'Carnegie Mellon University','Production-Operations Management');
Insert school_rank_in_program values(66,3,'Purdue University-West Lafayette','Production-Operations Management');
Insert school_rank_in_program values(26,4,'University of Michigan-Ann Arbor','Production-Operations Management');
Insert school_rank_in_program values(21,5,'University of California—​Berkeley','Production-Operations Management');
Insert school_rank_in_program values(5,6,'University of Pennsylvania','Production-Operations Management');
Insert school_rank_in_program values(58,7,'Ohio State University-Columbus','Production-Operations Management');
Insert school_rank_in_program values(72,8,'Michigan State University','Production-Operations Management');
Insert school_rank_in_program values(28,9,'University of North Carolina-Chapel Hill','Production-Operations Management');
Insert school_rank_in_program values(75,10,'Indiana University-Bloomington','Production-Operations Management');
Insert school_rank_in_program values(45,11,'University of Texas-Austin','Production-Operations Management');
Insert school_rank_in_program values(36,12,'Georgia Institute of Technology','Production-Operations Management');
Insert school_rank_in_program values(147,13,'University of Texas-Dallas','Production-Operations Management');
Insert school_rank_in_program values(34,14,'New York University','Production-Operations Management');
Insert school_rank_in_program values(23,15,'University of Virginia','Production-Operations Management');

Insert school_rank_in_program values(7,1,'Massachusetts Institute of Technology','Quantitative Analysis');
Insert school_rank_in_program values(22,2,'Carnegie Mellon University','Quantitative Analysis');
Insert school_rank_in_program values(5,3,'University of Pennsylvania','Quantitative Analysis');
Insert school_rank_in_program values(21,4,'University of California—​Berkeley','Quantitative Analysis');
Insert school_rank_in_program values(36,5,'Georgia Institute of Technology','Quantitative Analysis');
Insert school_rank_in_program values(66,6,'Purdue University-West Lafayette','Quantitative Analysis');
Insert school_rank_in_program values(34,7,'New York University','Quantitative Analysis');
Insert school_rank_in_program values(26,8,'University of Michigan-Ann Arbor','Quantitative Analysis');
Insert school_rank_in_program values(45,9,'University of Texas-Austin','Quantitative Analysis');
Insert school_rank_in_program values(49,10,'University of Florida','Quantitative Analysis');
Insert school_rank_in_program values(13,11,'Cornell University','Quantitative Analysis');
Insert school_rank_in_program values(75,11,'Indiana University-Bloomington','Quantitative Analysis');


Insert school_rank_in_program values(5,1,'University of Pennsylvania','Real Estate');
Insert school_rank_in_program values(38,2,'University of Wisconsin-Madison','Real Estate');
Insert school_rank_in_program values(60,3,'University of Georgia','Real Estate');
Insert school_rank_in_program values(21,4,'University of California—​Berkeley','Real Estate');
Insert school_rank_in_program values(27,5,'University of Southern California','Real Estate');
Insert school_rank_in_program values(34,6,'New York University','Real Estate');
Insert school_rank_in_program values(49,7,'University of Florida','Real Estate');
Insert school_rank_in_program values(45,8,'University of Texas-Austin','Real Estate');
Insert school_rank_in_program values(84,9,'Marquette University','Real Estate');
Insert school_rank_in_program values(112,10,'Florida State University','Real Estate');
Insert school_rank_in_program values(40,10,'University of Illinois-Urbana-Champaign','Real Estate');
Insert school_rank_in_program values(13,12,'Cornell University','Real Estate');
Insert school_rank_in_program values(65,13,'University of Connecticut','Real Estate');


Insert school_rank_in_program values(72,1,'Michigan State University','Supply Chain Management and Logistics');
Insert school_rank_in_program values(7,2,'Massachusetts Institute of Technology','Supply Chain Management and Logistics');
Insert school_rank_in_program values(58,3,'Ohio State University-Columbus','Supply Chain Management and Logistics');
Insert school_rank_in_program values(48,4,'Pennsylvania State University-University Park','Supply Chain Management and Logistics');
Insert school_rank_in_program values(127,5,'Arizona State University-Tempe','Supply Chain Management and Logistics');
Insert school_rank_in_program values(101,5,'University of Tennessee','Supply Chain Management and Logistics');
Insert school_rank_in_program values(22,7,'Carnegie Mellon University','Supply Chain Management and Logistics');
Insert school_rank_in_program values(26,8,'University of Michigan-Ann Arbor','Supply Chain Management and Logistics');
Insert school_rank_in_program values(66,9,'Purdue University-West Lafayette','Supply Chain Management and Logistics');
Insert school_rank_in_program values(56,10,'University of Maryland-College Park','Supply Chain Management and Logistics');
Insert school_rank_in_program values(45,11,'University of Texas-Austin','Supply Chain Management and Logistics');
Insert school_rank_in_program values(36,12,'Georgia Institute of Technology','Supply Chain Management and Logistics');
Insert school_rank_in_program values(21,13,'University of California—​Berkeley','Supply Chain Management and Logistics');
Insert school_rank_in_program values(84,14,'Marquette University','Supply Chain Management and Logistics');
Insert school_rank_in_program values(5,14,'University of Pennsylvania','Supply Chain Management and Logistics');
Insert school_rank_in_program values(126,16,'University of Arkansas-Fayetteville','Supply Chain Management and Logistics');
Insert school_rank_in_program values(75,17,'Indiana University-Bloomington','Supply Chain Management and Logistics');
Insert school_rank_in_program values(124,18,'Clarkson University','Supply Chain Management and Logistics');
Insert school_rank_in_program values(38,18,'University of Wisconsin-Madison','Supply Chain Management and Logistics');



commit;