DROP TABLE IF EXISTS school_speciality;
CREATE TABLE school_speciality
(
  School_Id INT NOT NULL,
  Rank INT,
  Score FLOAT,
  School_Name VARCHAR(80),
  Speciality VARCHAR(30),
  Primary Key (School_Id, Speciality),
  FOREIGN KEY (School_Id) REFERENCES school (Id)

);


Insert school_speciality values(7,1,4.8,'Massachusetts Institute of Technology','Engineering_Doctorate');
Insert school_speciality values(4,1,4.8,'Stanford University','Engineering_Doctorate');
Insert school_speciality values(21,3,4.7,'University of California—Berkeley','Engineering_Doctorate');
Insert school_speciality values(6,4,4.6,'California Institute of Technology','Engineering_Doctorate');
Insert school_speciality values(36,5,4.5,'Georgia Institute of Technology','Engineering_Doctorate');
Insert school_speciality values(40,5,4.4,'University of Illinois—Urbana-Champaign','Engineering_Doctorate');
Insert school_speciality values(22,6,4.3,'Carnegie Mellon University','Engineering_Doctorate');
Insert school_speciality values(26,6,4.3,'University of Michigan—Ann Arbor','Engineering_Doctorate');
Insert school_speciality values(13,9,4.2,'Cornell University','Engineering_Doctorate');
Insert school_speciality values(66,9,4.2,'Purdue University-West Lafayette','Engineering_Doctorate');
Insert school_speciality values(1,11,4.1,'Princeton University','Engineering_Doctorate');
Insert school_speciality values(45,11,4.1,'University of Texas-Austin','Engineering_Doctorate');
Insert school_speciality values(15,13,4.0,'Northwestern University','Engineering_Doctorate');
Insert school_speciality values(38,14,3.9,'University of Wisconsin-Madison','Engineering_Doctorate');
Insert school_speciality values(16,15,3.8,'Johns Hopkins University','Engineering_Doctorate');
Insert school_speciality values(62,15,3.8,'Texas A&M University-College Station','Engineering_Doctorate');
Insert school_speciality values(71,15,3.8,'Virginia Tech','Engineering_Doctorate');
Insert school_speciality values(9,18,3.7,'Columbia University','Engineering_Doctorate');
Insert school_speciality values(8,18,3.7,'Duke University','Engineering_Doctorate');
Insert school_speciality values(48,18,3.7,'Pennsylvania State University-University Park','Engineering_Doctorate');
Insert school_speciality values(17,18,3.7,'Rice University','Engineering_Doctorate');
Insert school_speciality values(25,18,3.7,'University of California-Los Angeles','Engineering_Doctorate');
Insert school_speciality values(39,23,3.6,'University of California-San Diego','Engineering_Doctorate');
Insert school_speciality values(56,23,3.6,'University of Maryland-College Park','Engineering_Doctorate');
Insert school_speciality values(74,23,3.6,'University of Minnesota-Twin Cities','Engineering_Doctorate');
Insert school_speciality values(42,23,3.6,'University of Washington','Engineering_Doctorate');
Insert school_speciality values(2,27,3.5,'Harvard University','Engineering_Doctorate');
Insert school_speciality values(58,27,3.5,'Ohio State University-Columbus','Engineering_Doctorate');
Insert school_speciality values(5,27,3.5,'University of Pennsylvania','Engineering_Doctorate');
Insert school_speciality values(27,27,3.5,'University of Southern California','Engineering_Doctorate');
Insert school_speciality values(89,31,3.4,'North Carolina State University-Raleigh','Engineering_Doctorate');
Insert school_speciality values(44,31,3.4,'Rensselaer Polytechnic Institute','Engineering_Doctorate');
Insert school_speciality values(43,31,3.4,'University of California-Davis','Engineering_Doctorate');
Insert school_speciality values(46,31,3.4,'University of California-Santa Barbara','Engineering_Doctorate');
Insert school_speciality values(23,31,3.4,'University of Virginia','Engineering_Doctorate');
Insert school_speciality values(86,36,3.3,'Iowa State University','Engineering_Doctorate');
Insert school_speciality values(80,36,3.3,'University of Colorado-Boulder','Engineering_Doctorate');
Insert school_speciality values(49,36,3.3,'University of Florida','Engineering_Doctorate');
Insert school_speciality values(19,36,3.3,'Vanderbilt University','Engineering_Doctorate');
Insert school_speciality values(3,36,3.3,'Yale University','Engineering_Doctorate');
Insert school_speciality values(127,41,3.2,'Arizona State University-Tempe','Engineering_Doctorate');
Insert school_speciality values(14,41,3.2,'Brown University ','Engineering_Doctorate');
Insert school_speciality values(41,41,3.2,'Case Western Reserve University','Engineering_Doctorate');
Insert school_speciality values(78,41,3.2,'Colorado School of Mines','Engineering_Doctorate');
Insert school_speciality values(31,41,3.2,'Lehigh University','Engineering_Doctorate');
Insert school_speciality values(20,41,3.2,'University of Notre Dame','Engineering_Doctorate');
Insert school_speciality values(12,41,3.2,'Washington University in St. Louis','Engineering_Doctorate');
Insert school_speciality values(11,48,3.1,'Dartmouth College','Engineering_Doctorate');
Insert school_speciality values(72,48,3.1,'Michigan State University','Engineering_Doctorate');
Insert school_speciality values(47,48,3.1,'University of California-Irvine','Engineering_Doctorate');
Insert school_speciality values(57,51,3.0,'Boston University','Engineering_Doctorate');
Insert school_speciality values(97,51,3.0,'Northeastern University','Engineering_Doctorate');
Insert school_speciality values(59,51,3.0,'Rutgers, the State University of New Jersey-New Brunswick','Engineering_Doctorate');
Insert school_speciality values(105,51,3.0,'University of Arizona','Engineering_Doctorate');
Insert school_speciality values(61,51,3.0,'University of Pittsburgh','Engineering_Doctorate');
Insert school_speciality values(142,56,2.9,'Auburn University','Engineering_Doctorate');
Insert school_speciality values(68,56,2.9,'Clemson University','Engineering_Doctorate');
Insert school_speciality values(108,56,2.9,'Drexel University','Engineering_Doctorate');
Insert school_speciality values(29,56,2.9,'Tufts University','Engineering_Doctorate');
Insert school_speciality values(73,56,2.9,'University of Delaware','Engineering_Doctorate');
Insert school_speciality values(96,56,2.9,'University of Massachusetts-Amherst','Engineering_Doctorate');
Insert school_speciality values(132,56,2.9,'University of Utah','Engineering_Doctorate');
Insert school_speciality values(100,63,2.8,'Illinois Institute of Technology','Engineering_Doctorate');
Insert school_speciality values(2006,63,2.8,'Rochester Institute of Technology','Engineering_Doctorate');
Insert school_speciality values(99,63,2.8,'SUNY-Stony Brook','Engineering_Doctorate');
Insert school_speciality values(118,63,2.8,'University at Buffalo-SUNY','Engineering_Doctorate');
Insert school_speciality values(64,63,2.8,'University of Iowa','Engineering_Doctorate');
Insert school_speciality values(101,63,2.8,'University of Tennessee','Engineering_Doctorate');
Insert school_speciality values(63,63,2.8,'Worcester Polytechnic Institute','Engineering_Doctorate');
Insert school_speciality values(125,70,2.7,'Colorado State University','Engineering_Doctorate');
Insert school_speciality values(123,70,2.7,'Kansas State University','Engineering_Doctorate');
Insert school_speciality values(128,70,2.7,'Michigan Technological University','Engineering_Doctorate');
Insert school_speciality values(117,70,2.7,'Missouri University of Science & Technology','Engineering_Doctorate');
Insert school_speciality values(34,70,2.7,'New York University','Engineering_Doctorate');
Insert school_speciality values(143,70,2.7,'Oregon State University','Engineering_Doctorate');
Insert school_speciality values(77,70,2.7,'Stevens Institute of Technology','Engineering_Doctorate');
Insert school_speciality values(51,70,2.7,'Syracuse University','Engineering_Doctorate');
Insert school_speciality values(65,70,2.7,'University of Connecticut','Engineering_Doctorate');
Insert school_speciality values(136,70,2.7,'University of Illinois-Chicago','Engineering_Doctorate');
Insert school_speciality values(85,70,2.7,'University of Kansas','Engineering_Doctorate');
Insert school_speciality values(35,70,2.7,'University of Rochester','Engineering_Doctorate');
Insert school_speciality values(119,70,2.7,'Washington State University','Engineering_Doctorate');
Insert school_speciality values(124,83,2.6,'Clarkson University','Engineering_Doctorate');
Insert school_speciality values(122,83,2.6,'New Jersey Institute of Technology','Engineering_Doctorate');
Insert school_speciality values(103,83,2.6,'University of California-Riverside','Engineering_Doctorate');
Insert school_speciality values(145,83,2.6,'University of Cincinnati','Engineering_Doctorate');
Insert school_speciality values(79,87,2.5,'Brigham Young University-Provo','Engineering_Doctorate');
Insert school_speciality values(138,87,2.5,'Louisiana State University-Baton Rouge','Engineering_Doctorate');
Insert school_speciality values(150,87,2.5,'Oklahoma State University','Engineering_Doctorate');
Insert school_speciality values(169,87,2.5,'Texas Tech University','Engineering_Doctorate');
Insert school_speciality values(189,87,2.5,'University of Houston','Engineering_Doctorate');
Insert school_speciality values(120,87,2.5,'University of Kentucky','Engineering_Doctorate');
Insert school_speciality values(92,87,2.5,'University of Missouri','Engineering_Doctorate');
Insert school_speciality values(95,87,2.5,'University of Nebraska','Engineering_Doctorate');
Insert school_speciality values(182,87,2.5,'University of New Mexico','Engineering_Doctorate');
Insert school_speciality values(110,87,2.5,'University of Oklahoma','Engineering_Doctorate');
Insert school_speciality values(147,87,2.5,'University of Texas-Dallas','Engineering_Doctorate');
Insert school_speciality values(54,98,2.4,'George Washington University','Engineering_Doctorate');
Insert school_speciality values(165,98,2.4,'Mississippi State University','Engineering_Doctorate');
Insert school_speciality values(151,98,2.4,'San Diego State University','Engineering_Doctorate');
Insert school_speciality values(67,98,2.4,'Southern Methodist University','Engineering_Doctorate');
Insert school_speciality values(93,98,2.4,'University of Alabama','Engineering_Doctorate');
Insert school_speciality values(126,98,2.4,'University of Arkansas','Engineering_Doctorate');
Insert school_speciality values(170,98,2.4,'University of Central Florida','Engineering_Doctorate');
Insert school_speciality values(198,98,2.4,'University of North Carolina-Charlotte','Engineering_Doctorate');
Insert school_speciality values(259,98,2.4,'University of Texas-Arlington','Engineering_Doctorate');
Insert school_speciality values(264,98,2.4,'University of Wisconsin-Milwaukee','Engineering_Doctorate');
Insert school_speciality values(2065,108,2.3,'CUNY-City College','Engineering_Doctorate');
Insert school_speciality values(139,108,2.3,'George Mason University','Engineering_Doctorate');
Insert school_speciality values(102,108,2.3,'Howard University','Engineering_Doctorate');
Insert school_speciality values(200,108,2.3,'Indiana University-Purdue University-Indianapolis','Engineering_Doctorate');
Insert school_speciality values(129,108,2.3,'Temple University','Engineering_Doctorate');
Insert school_speciality values(50,108,2.3,'Tulane University','Engineering_Doctorate');
Insert school_speciality values(188,108,2.3,'University of Alabama-Huntsville','Engineering_Doctorate');
Insert school_speciality values(81,108,2.3,'University of California-Santa Cruz','Engineering_Doctorate');
Insert school_speciality values(156,108,2.3,'University of Maryland-Baltimore County','Engineering_Doctorate');
Insert school_speciality values(157,108,2.3,'University of Massachusetts-Lowell','Engineering_Doctorate');
Insert school_speciality values(52,108,2.3,'University of Miami','Engineering_Doctorate');
Insert school_speciality values(167,108,2.3,'University of Rhode Island','Engineering_Doctorate');
Insert school_speciality values(113,108,2.3,'University of South Carolina','Engineering_Doctorate');
Insert school_speciality values(265,108,2.3,'Utah State University','Engineering_Doctorate');
Insert school_speciality values(179,108,2.3,'West Virginia University','Engineering_Doctorate');
Insert school_speciality values(82,124,2.2,'SUNY-Binghamton','Engineering_Doctorate');
Insert school_speciality values(201,124,2.2,'Louisiana Tech University','Engineering_Doctorate');
Insert school_speciality values(84,124,2.2,'Marquette University','Engineering_Doctorate');
Insert school_speciality values(202,124,2.2,'New Mexico State University','Engineering_Doctorate');
Insert school_speciality values(116,124,2.2,'Ohio University','Engineering_Doctorate');
Insert school_speciality values(10006,124,2.2,'South Dakota School of Mines and Technology','Engineering_Doctorate');
Insert school_speciality values(166,124,2.2,'University of Hawaii-Manoa','Engineering_Doctorate');
Insert school_speciality values(109,124,2.2,'University of New Hampshire','Engineering_Doctorate');
Insert school_speciality values(158,124,2.2,'University of South Florida','Engineering_Doctorate');
Insert school_speciality values(98,124,2.2,'University of Vermont','Engineering_Doctorate');
Insert school_speciality values(159,124,2.2,'Virginia Commonwealth University','Engineering_Doctorate');
Insert school_speciality values(266,124,2.2,'Wayne State University','Engineering_Doctorate');
Insert school_speciality values(267,124,2.2,'Wichita State University','Engineering_Doctorate');
Insert school_speciality values(211,137,2.1,'Florida A&M University','Engineering_Doctorate');
Insert school_speciality values(222,137,2.1,'Montana State University','Engineering_Doctorate');
Insert school_speciality values(3025,137,2.1,'New Mexico Institute of Mining and Technology','Engineering_Doctorate');
Insert school_speciality values(225,137,2.1,'North Carolina A&T State University','Engineering_Doctorate');
Insert school_speciality values(230,137,2.1,'Old Dominion University','Engineering_Doctorate');
Insert school_speciality values(244,137,2.1,'University of Akron','Engineering_Doctorate');
Insert school_speciality values(152,137,2.1,'University of Alabama-Birmingham','Engineering_Doctorate');
Insert school_speciality values(203,137,2.1,'University of Colorado-Denver','Engineering_Doctorate');
Insert school_speciality values(115,137,2.1,'University of Dayton','Engineering_Doctorate');
Insert school_speciality values(60,137,2.1,'University of Georgia','Engineering_Doctorate');
Insert school_speciality values(171,137,2.1,'University of Idaho','Engineering_Doctorate');
Insert school_speciality values(190,137,2.1,'University of Nevada-Reno','Engineering_Doctorate');
Insert school_speciality values(94,137,2.1,'University of Tulsa','Engineering_Doctorate');
Insert school_speciality values(174,137,2.1,'University of Wyoming','Engineering_Doctorate');
Insert school_speciality values(268,137,2.1,'Wright State University','Engineering_Doctorate');
Insert school_speciality values(2046,152,2.0,'Alfred University','Engineering_Doctorate');
Insert school_speciality values(162,152,2.0,'Florida Institute of Technology','Engineering_Doctorate');
Insert school_speciality values(274,152,2.0,'Idaho State University','Engineering_Doctorate');
Insert school_speciality values(232,152,2.0,'Portland State University','Engineering_Doctorate');
Insert school_speciality values(83,152,2.0,'Saint Louis University','Engineering_Doctorate');
Insert school_speciality values(5036,152,2.0,'Tennessee Technological University','Engineering_Doctorate');
Insert school_speciality values(245,152,2.0,'University of Alaska-Fairbanks','Engineering_Doctorate');
Insert school_speciality values(173,152,2.0,'University of Maine','Engineering_Doctorate');
Insert school_speciality values(249,152,2.0,'University of Memphis','Engineering_Doctorate');
Insert school_speciality values(146,152,2.0,'University of Mississippi','Engineering_Doctorate');
Insert school_speciality values(253,152,2.0,'University of Nevada-Las Vegas','Engineering_Doctorate');
Insert school_speciality values(260,152,2.0,'University of Texas-El Paso','Engineering_Doctorate');
Insert school_speciality values(261,152,2.0,'University of Texas-San Antonio','Engineering_Doctorate');
Insert school_speciality values(262,152,2.0,'University of Toledo','Engineering_Doctorate');
Insert school_speciality values(121,166,1.9,'Catholic University of America','Engineering_Doctorate');
Insert school_speciality values(209,166,1.9,'Cleveland State University','Engineering_Doctorate');
Insert school_speciality values(213,166,1.9,'Florida International University','Engineering_Doctorate');
Insert school_speciality values(186,166,1.9,'North Dakota State University','Engineering_Doctorate');
Insert school_speciality values(187,166,1.9,'South Dakota State University','Engineering_Doctorate');
Insert school_speciality values(154,166,1.9,'Southern Illinois University-Carbondale','Engineering_Doctorate');
Insert school_speciality values(90,166,1.9,'SUNY College of Environmental Science and Forestry','Engineering_Doctorate');
Insert school_speciality values(88,166,1.9,'University of Denver','Engineering_Doctorate');
Insert school_speciality values(197,166,1.9,'University of Missouri-Kansas City','Engineering_Doctorate');
Insert school_speciality values(183,166,1.9,'University of North Dakota','Engineering_Doctorate');
Insert school_speciality values(212,176,1.8,'Florida Atlantic University','Engineering_Doctorate');
Insert school_speciality values(223,176,1.8,'Morgan State University','Engineering_Doctorate');
Insert school_speciality values(236,176,1.8,'Tennessee State University','Engineering_Doctorate');
Insert school_speciality values(239,176,1.8,'Texas A&M University-Kingsville','Engineering_Doctorate');
Insert school_speciality values(247,176,1.8,'University of Louisiana-Lafayette','Engineering_Doctorate');
Insert school_speciality values(192,176,1.8,'Western Michigan University','Engineering_Doctorate');
Insert school_speciality values(219,182,1.7,'Lamar University','Engineering_Doctorate');
Insert school_speciality values(229,182,1.7,'Oakland University','Engineering_Doctorate');
Insert school_speciality values(254,184,1.6,'University of New Orleans','Engineering_Doctorate');



Insert school_speciality values(1014,1,4.4,'Harvey Mudd College','Engineering_No_Doctorate');
Insert school_speciality values(10003,1,4.4,'Rose-Hulman Institute of Technology','Engineering_No_Doctorate');
Insert school_speciality values(10001,3,4.1,'Franklin W. Olin College of Engineering','Engineering_No_Doctorate');
Insert school_speciality values(1021,3,4.1,'United States Military Academy','Engineering_No_Doctorate');
Insert school_speciality values(1030,5,3.9,'United States Air Force Academy','Engineering_No_Doctorate');
Insert school_speciality values(1010,5,3.9,'United States Naval Academy','Engineering_No_Doctorate');
Insert school_speciality values(3009,7,3.8,'California Polytechnic State University-San Luis Obispo','Engineering_No_Doctorate');
Insert school_speciality values(1031,8,3.7,'Bucknell University','Engineering_No_Doctorate');
Insert school_speciality values(6001,8,3.7,'Cooper Union','Engineering_No_Doctorate');
Insert school_speciality values(5009,8,3.7,'Embry-Riddle Aeronautical University','Engineering_No_Doctorate');
Insert school_speciality values(2000,11,3.5,'Villanova University','Engineering_No_Doctorate');
Insert school_speciality values(76,12,3.4,'Baylor University','Engineering_No_Doctorate');
Insert school_speciality values(4015,12,3.4,'Milwaukee School of Engineering','Engineering_No_Doctorate');
Insert school_speciality values(3001,12,3.4,'Santa Clara University','Engineering_No_Doctorate');
Insert school_speciality values(3030,15,3.3,'California State Polytechnic University-Pomona','Engineering_No_Doctorate');
Insert school_speciality values(5133,15,3.3,'Embry-Riddle Aeronautical University-Prescott','Engineering_No_Doctorate');
Insert school_speciality values(4024,15,3.3,'Kettering University','Engineering_No_Doctorate');
Insert school_speciality values(1036,15,3.3,'Lafayette College','Engineering_No_Doctorate');
Insert school_speciality values(1002,15,3.3,'Swarthmore College','Engineering_No_Doctorate');
Insert school_speciality values(6000,15,3.3,'United States Coast Guard Academy','Engineering_No_Doctorate');
Insert school_speciality values(106,15,3.3,'University of San Diego','Engineering_No_Doctorate');
Insert school_speciality values(5002,22,3.2,'The Citadel','Engineering_No_Doctorate');
Insert school_speciality values(4056,22,3.2,'Lawrence Technological University','Engineering_No_Doctorate');
Insert school_speciality values(1015,22,3.2,'Smith College','Engineering_No_Doctorate');
Insert school_speciality values(1038,22,3.2,'Union College','Engineering_No_Doctorate');
Insert school_speciality values(3046,22,3.2,'University of Colorado-Colorado Springs','Engineering_No_Doctorate');
Insert school_speciality values(4004,22,3.2,'Valparaiso University','Engineering_No_Doctorate');
Insert school_speciality values(1087,22,3.2,'Virginia Military Institute','Engineering_No_Doctorate');
Insert school_speciality values(3003,28,3.1,'Gonzaga University','Engineering_No_Doctorate');
Insert school_speciality values(3002,28,3.1,'Loyola Marymount University','Engineering_No_Doctorate');
Insert school_speciality values(2020,28,3.1,'Rowan University','Engineering_No_Doctorate');
Insert school_speciality values(3040,28,3.1,'San Jose State University','Engineering_No_Doctorate');
Insert school_speciality values(6002,28,3.1,'United States Merchant Marine Academy','Engineering_No_Doctorate');
Insert school_speciality values(3060,33,3.0,'Boise State University','Engineering_No_Doctorate');
Insert school_speciality values(4003,33,3.0,'Bradley University','Engineering_No_Doctorate');
Insert school_speciality values(70,33,3.0,'Miami University-Oxford','Engineering_No_Doctorate');
Insert school_speciality values(3005,33,3.0,'Seattle University','Engineering_No_Doctorate');
Insert school_speciality values(3000,33,3.0,'Trinity University','Engineering_No_Doctorate');
Insert school_speciality values(7012,39,2.9,'Brigham Young University-Idaho','Engineering_No_Doctorate');
Insert school_speciality values(3062,39,2.9,'California State University-Los Angeles','Engineering_No_Doctorate');
Insert school_speciality values(3032,39,2.9,'LeTourneau University','Engineering_No_Doctorate');
Insert school_speciality values(5008,39,2.9,'Mercer University','Engineering_No_Doctorate');
Insert school_speciality values(8002,39,2.9,'Ohio Northern University','Engineering_No_Doctorate');
Insert school_speciality values(2087,39,2.9,'University of Massachusetts-Dartmouth','Engineering_No_Doctorate');
Insert school_speciality values(4039,39,2.9,'University of Michigan-Dearborn','Engineering_No_Doctorate');
Insert school_speciality values(3031,46,2.8,'California State University-Long Beach','Engineering_No_Doctorate');
Insert school_speciality values(3069,46,2.8,'California State University-Northridge','Engineering_No_Doctorate');
Insert school_speciality values(4026,46,2.8,'Grand Valley State University','Engineering_No_Doctorate');
Insert school_speciality values(2004,46,2.8,'Loyola University Maryland','Engineering_No_Doctorate');
Insert school_speciality values(227,46,2.8,'Northern Illinois University','Engineering_No_Doctorate');
Insert school_speciality values(7006,46,2.8,'Oregon Institute of Technology','Engineering_No_Doctorate');
Insert school_speciality values(1043,46,2.8,'Trinity College','Engineering_No_Doctorate');
Insert school_speciality values(3077,46,2.8,'University of Alaska-Anchorage','Engineering_No_Doctorate');
Insert school_speciality values(4040,46,2.8,'University of Minnesota-Duluth','Engineering_No_Doctorate');
Insert school_speciality values(3007,46,2.8,'University of Portland','Engineering_No_Doctorate');
Insert school_speciality values(3029,46,2.8,'University of St. Thomas','Engineering_No_Doctorate');
Insert school_speciality values(4084,46,2.8,'University of Wisconsin-Platteville','Engineering_No_Doctorate');
Insert school_speciality values(7007,58,2.7,'California Maritime Academy','Engineering_No_Doctorate');
Insert school_speciality values(3036,58,2.7,'California State University-Fullerton','Engineering_No_Doctorate');
Insert school_speciality values(1120,58,2.7,'Calvin College','Engineering_No_Doctorate');
Insert school_speciality values(8008,58,2.7,'Cedarville University','Engineering_No_Doctorate');
Insert school_speciality values(140,58,2.7,'Hofstra University','Engineering_No_Doctorate');
Insert school_speciality values(1100,58,2.7,'Hope College','Engineering_No_Doctorate');
Insert school_speciality values(3057,58,2.7,'Humboldt State University','Engineering_No_Doctorate');
Insert school_speciality values(4126,58,2.7,'Indiana University-Purdue University-Fort Wayne','Engineering_No_Doctorate');
Insert school_speciality values(5007,58,2.7,'James Madison University','Engineering_No_Doctorate');
Insert school_speciality values(6006,58,2.7,'Maine Maritime Academy','Engineering_No_Doctorate');
Insert school_speciality values(2016,58,2.7,'Manhattan College','Engineering_No_Doctorate');
Insert school_speciality values(7005,58,2.7,'Montana Tech of the University of Montana','Engineering_No_Doctorate');
Insert school_speciality values(226,58,2.7,'Northern Arizona University','Engineering_No_Doctorate');
Insert school_speciality values(6073,58,2.7,'Pennsylvania State University-Erie, The Behrend College','Engineering_No_Doctorate');
Insert school_speciality values(4141,58,2.7,'Purdue University-Calumet','Engineering_No_Doctorate');
Insert school_speciality values(107,58,2.7,'Texas Christian University','Engineering_No_Doctorate');
Insert school_speciality values(246,58,2.7,'University of Arkansas-Little Rock','Engineering_No_Doctorate');
Insert school_speciality values(256,58,2.7,'University of North Texas','Engineering_No_Doctorate');
Insert school_speciality values(5060,58,2.7,'University of Tennessee-Chattanooga','Engineering_No_Doctorate');
Insert school_speciality values(104,58,2.7,'University of the Pacific','Engineering_No_Doctorate');
Insert school_speciality values(6075,58,2.7,'West Virginia University Institute of Technology','Engineering_No_Doctorate');
Insert school_speciality values(4149,58,2.7,'Youngstown State University','Engineering_No_Doctorate');
Insert school_speciality values(3051,80,2.6,'California State University-Fresno','Engineering_No_Doctorate');
Insert school_speciality values(3064,80,2.6,'California State University-Sacramento','Engineering_No_Doctorate');
Insert school_speciality values(2003,80,2.6,'College of New Jersey','Engineering_No_Doctorate');
Insert school_speciality values(2058,80,2.6,'Gannon University','Engineering_No_Doctorate');
Insert school_speciality values(1133,80,2.6,'Grove City College','Engineering_No_Doctorate');
Insert school_speciality values(6004,80,2.6,'Messiah College','Engineering_No_Doctorate');
Insert school_speciality values(2043,80,2.6,'New York Institute of Technology','Engineering_No_Doctorate');
Insert school_speciality values(4077,80,2.6,'Minnesota State University-Mankato','Engineering_No_Doctorate');
Insert school_speciality values(2073,80,2.6,'Norwich University','Engineering_No_Doctorate');
Insert school_speciality values(2037,80,2.6,'Roger Williams University','Engineering_No_Doctorate');
Insert school_speciality values(3066,80,2.6,'San Francisco State University','Engineering_No_Doctorate');
Insert school_speciality values(3053,80,2.6,'Texas State University','Engineering_No_Doctorate');
Insert school_speciality values(3146,80,2.6,'California State University-Merced','Engineering_No_Doctorate');
Insert school_speciality values(2096,80,2.6,'University of Hartford','Engineering_No_Doctorate');
Insert school_speciality values(250,80,2.6,'University of Missouri-St. Louis','Engineering_No_Doctorate');
Insert school_speciality values(2097,80,2.6,'University of New Haven','Engineering_No_Doctorate');
Insert school_speciality values(10002,80,2.6,'Webb Institute','Engineering_No_Doctorate');
Insert school_speciality values(6012,80,2.6,'Wentworth Institute of Technology','Engineering_No_Doctorate');
Insert school_speciality values(3042,98,2.5,'California State University-Chico','Engineering_No_Doctorate');
Insert school_speciality values(194,98,2.5,'Central Michigan University','Engineering_No_Doctorate');
Insert school_speciality values(3065,98,2.5,'Eastern Washington University','Engineering_No_Doctorate');
Insert school_speciality values(5080,98,2.5,'Florida Gulf Coast University','Engineering_No_Doctorate');
Insert school_speciality values(6015,98,2.5,'Geneva College','Engineering_No_Doctorate');
Insert school_speciality values(6008,98,2.5,'Merrimack College','Engineering_No_Doctorate');
Insert school_speciality values(6074,98,2.5,'Pennsylvania State University-Harrisburg','Engineering_No_Doctorate');
Insert school_speciality values(3018,98,2.5,'Seattle Pacific University','Engineering_No_Doctorate');
Insert school_speciality values(4045,98,2.5,'Southern Illinois University-Edwardsville','Engineering_No_Doctorate');
Insert school_speciality values(6016,98,2.5,'SUNY Maritime College','Engineering_No_Doctorate');
Insert school_speciality values(4025,98,2.5,'University of Detroit Mercy','Engineering_No_Doctorate');
Insert school_speciality values(4008,98,2.5,'University of Evansville','Engineering_No_Doctorate');
Insert school_speciality values(4067,98,2.5,'University of Wisconsin-Stout','Engineering_No_Doctorate');
Insert school_speciality values(3078,98,2.5,'Weber State University','Engineering_No_Doctorate');
Insert school_speciality values(2064,98,2.5,'Western New England University','Engineering_No_Doctorate');
Insert school_speciality values(5098,114,2.4,'Alabama Agricultural and Mechanical University','Engineering_No_Doctorate');
Insert school_speciality values(5053,114,2.4,'Arkansas State University','Engineering_No_Doctorate');
Insert school_speciality values(3096,114,2.4,'Colorado State University-Pueblo','Engineering_No_Doctorate');
Insert school_speciality values(2148,114,2.4,'CUNY-College of Staten Island','Engineering_No_Doctorate');
Insert school_speciality values(8006,114,2.4,'Dordt College','Engineering_No_Doctorate');
Insert school_speciality values(2005,114,2.4,'Fairfield University','Engineering_No_Doctorate');
Insert school_speciality values(2084,114,2.4,'Fairleigh Dickinson University','Engineering_No_Doctorate');
Insert school_speciality values(8056,114,2.4,'Lake Superior State University','Engineering_No_Doctorate');
Insert school_speciality values(5045,114,2.4,'Marshall University','Engineering_No_Doctorate');
Insert school_speciality values(5030,114,2.4,'Murray State University','Engineering_No_Doctorate');
Insert school_speciality values(8090,114,2.4,'Purdue University-North Central','Engineering_No_Doctorate');
Insert school_speciality values(4102,114,2.4,'St. Cloud State University','Engineering_No_Doctorate');
Insert school_speciality values(237,114,2.4,'Texas A&M University-Commerce','Engineering_No_Doctorate');
Insert school_speciality values(8030,114,2.4,'Trine University','Engineering_No_Doctorate');
Insert school_speciality values(9009,114,2.4,'Tuskegee University','Engineering_No_Doctorate');
Insert school_speciality values(1150,114,2.4,'University of North Carolina-Asheville','Engineering_No_Doctorate');
Insert school_speciality values(5051,114,2.4,'University of North Florida','Engineering_No_Doctorate');
Insert school_speciality values(257,114,2.4,'University of South Alabama','Engineering_No_Doctorate');
Insert school_speciality values(5126,114,2.4,'Virginia State University','Engineering_No_Doctorate');
Insert school_speciality values(193,114,2.4,'Widener University','Engineering_No_Doctorate');
Insert school_speciality values(5087,134,2.3,'Arkansas Tech University','Engineering_No_Doctorate');
Insert school_speciality values(3038,134,2.3,'California Baptist University','Engineering_No_Doctorate');
Insert school_speciality values(4061,134,2.3,'Ferris State University','Engineering_No_Doctorate');
Insert school_speciality values(214,134,2.3,'Georgia Southern University','Engineering_No_Doctorate');
Insert school_speciality values(10013,134,2.3,'Indiana Institute of Technology','Engineering_No_Doctorate');
Insert school_speciality values(5072,134,2.3,'Kennesaw State University','Engineering_No_Doctorate');
Insert school_speciality values(8004,134,2.3,'Marietta College','Engineering_No_Doctorate');
Insert school_speciality values(2068,134,2.3,'Robert Morris University-PA','Engineering_No_Doctorate');
Insert school_speciality values(4038,134,2.3,'St. Ambrose University','Engineering_No_Doctorate');
Insert school_speciality values(2024,134,2.3,'SUNY-New Paltz','Engineering_No_Doctorate');
Insert school_speciality values(8000,134,2.3,'Taylor University','Engineering_No_Doctorate');
Insert school_speciality values(238,134,2.3,'Texas A&M University-Corpus Christi','Engineering_No_Doctorate');
Insert school_speciality values(5015,134,2.3,'Union University','Engineering_No_Doctorate');
Insert school_speciality values(2178,134,2.3,'University of Bridgeport','Engineering_No_Doctorate');
Insert school_speciality values(3075,134,2.3,'University of Texas-Tyler','Engineering_No_Doctorate');
Insert school_speciality values(4051,134,2.3,'University of Wisconsin-Stevens Point','Engineering_No_Doctorate');
Insert school_speciality values(5031,134,2.3,'Western Kentucky University','Engineering_No_Doctorate');
Insert school_speciality values(3093,151,2.2,'California State University-East Bay','Engineering_No_Doctorate');
Insert school_speciality values(3068,151,2.2,'California State University-San Bernardino','Engineering_No_Doctorate');
Insert school_speciality values(2106,151,2.2,'Central Connecticut State University','Engineering_No_Doctorate');
Insert school_speciality values(5027,151,2.2,'Christian Brothers University','Engineering_No_Doctorate');
Insert school_speciality values(273,151,2.2,'Colorado Technical University','Engineering_No_Doctorate');
Insert school_speciality values(195,151,2.2,'East Carolina University','Engineering_No_Doctorate');
Insert school_speciality values(5022,151,2.2,'Harding University','Engineering_No_Doctorate');
Insert school_speciality values(218,151,2.2,'Jackson State University','Engineering_No_Doctorate');
Insert school_speciality values(9001,151,2.2,'John Brown University','Engineering_No_Doctorate');
Insert school_speciality values(5019,151,2.2,'Lipscomb University','Engineering_No_Doctorate');
Insert school_speciality values(2036,151,2.2,'Monmouth University','Engineering_No_Doctorate');
Insert school_speciality values(5114,151,2.2,'Norfolk State University','Engineering_No_Doctorate');
Insert school_speciality values(4058,151,2.2,'Olivet Nazarene University','Engineering_No_Doctorate');
Insert school_speciality values(2062,151,2.2,'Philadelphia University','Engineering_No_Doctorate');
Insert school_speciality values(3107,151,2.2,'Prairie View A&M University','Engineering_No_Doctorate');
Insert school_speciality values(4142,151,2.2,'Saginaw Valley State University','Engineering_No_Doctorate');
Insert school_speciality values(4094,151,2.2,'Southeast Missouri State University','Engineering_No_Doctorate');
Insert school_speciality values(3070,151,2.2,'Southern Utah University','Engineering_No_Doctorate');
Insert school_speciality values(3021,151,2.2,'St. Marys University of San Antonio','Engineering_No_Doctorate');
Insert school_speciality values(3081,151,2.2,'University of Houston-Clear Lake','Engineering_No_Doctorate');
Insert school_speciality values(4103,158,2.2,'University of Michigan-Flint','Engineering_No_Doctorate');
Insert school_speciality values(2007,158,2.2,'University of Scranton','Engineering_No_Doctorate');
Insert school_speciality values(2180,158,2.2,'University of Southern Maine','Engineering_No_Doctorate');
Insert school_speciality values(5052,158,2.2,'University of Tennessee-Martin','Engineering_No_Doctorate');
Insert school_speciality values(1228,158,2.2,'University of Virginia-Wise','Engineering_No_Doctorate');
Insert school_speciality values(263,158,2.2,'University of West Florida','Engineering_No_Doctorate');
Insert school_speciality values(5034,158,2.2,'Western Carolina University','Engineering_No_Doctorate');
Insert school_speciality values(3128,158,2.2,'West Texas A&M University','Engineering_No_Doctorate');
Insert school_speciality values(4073,158,2.2,'Winona State University','Engineering_No_Doctorate');
Insert school_speciality values(2090,158,2.2,'York College of Pennsylvania','Engineering_No_Doctorate');
Insert school_speciality values(7000,181,2.1,'Carroll College','Engineering_No_Doctorate');
Insert school_speciality values(5014,181,2.1,'Christopher Newport University','Engineering_No_Doctorate');
Insert school_speciality values(2127,181,2.1,'Frostburg State University','Engineering_No_Doctorate');
Insert school_speciality values(5018,181,2.1,'Hampton University','Engineering_No_Doctorate');
Insert school_speciality values(5089,181,2.1,'McNeese State University','Engineering_No_Doctorate');
Insert school_speciality values(3043,181,2.1,'Oklahoma Christian University','Engineering_No_Doctorate');
Insert school_speciality values(3013,181,2.1,'Pacific Lutheran University','Engineering_No_Doctorate');
Insert school_speciality values(3045,181,2.1,'St. Martin-s University','Engineering_No_Doctorate');
Insert school_speciality values(2061,181,2.1,'Suffolk University','Engineering_No_Doctorate');
Insert school_speciality values(2179,181,2.1,'University of Maryland-Eastern Shore','Engineering_No_Doctorate');
Insert school_speciality values(3126,181,2.1,'University of Texas of the Permian Basin','Engineering_No_Doctorate');
Insert school_speciality values(2089,181,2.1,'Wilkes University','Engineering_No_Doctorate');
Insert school_speciality values(6053,193,2.0,'Daniel Webster College','Engineering_No_Doctorate');
Insert school_speciality values(6003,193,2.0,'Elizabethtown College','Engineering_No_Doctorate');
Insert school_speciality values(3027,193,2.0,'George Fox UniversityGeorge Fox University','Engineering_No_Doctorate');
Insert school_speciality values(3103,193,2.0,'Midwestern State University','Engineering_No_Doctorate');
Insert school_speciality values(4050,193,2.0,'Muskingum University','Engineering_No_Doctorate');
Insert school_speciality values(196,193,2.0,'South Carolina State University','Engineering_No_Doctorate');
Insert school_speciality values(3080,193,2.0,'University of Central Oklahoma','Engineering_No_Doctorate');
Insert school_speciality values(4146,193,2.0,'University of Southern Indiana','Engineering_No_Doctorate');
Insert school_speciality values(2181,193,2.0,'University of the District of Columbia','Engineering_No_Doctorate');
Insert school_speciality values(3044,193,2.0,'Walla Walla University','Engineering_No_Doctorate');
Insert school_speciality values(4048,193,2.0,'Western Illinois University','Engineering_No_Doctorate');
Insert school_speciality values(8012,205,1.9,'Loras College','Engineering_No_Doctorate');
Insert school_speciality values(3050,205,1.9,'Oral Roberts University','Engineering_No_Doctorate');
Insert school_speciality values(5120,205,1.9,'Southern University and A&M College','Engineering_No_Doctorate');
Insert school_speciality values(2045,205,1.9,'St. Francis University','Engineering_No_Doctorate');
Insert school_speciality values(6026,205,1.9,'Vaughn College of Aeronautics and Technology','Engineering_No_Doctorate');
Insert school_speciality values(1196,210,1.8,'Fort Lewis College','Engineering_No_Doctorate');
Insert school_speciality values(5081,210,1.8,'Liberty University','Engineering_No_Doctorate');
Insert school_speciality values(175,212,1.7,'Andrews University','Engineering_No_Doctorate');
Insert school_speciality values(3123,212,1.7,'Tarleton State University','Engineering_No_Doctorate');
Insert school_speciality values(8094,214,1.6,'Baker College of Flint','Engineering_No_Doctorate');
Insert school_speciality values(8074,214,1.6,'Central State University','Engineering_No_Doctorate');


Insert school_speciality values(5,1,4.8,'University of Pennsylvania','Business');
Insert school_speciality values(7,2,4.6,'Massachusetts Institute of Technology','Business');
Insert school_speciality values(21,2,4.6,'University of California—Berkeley','Business');
Insert school_speciality values(26,4,4.5,'University of Michigan—Ann Arbor','Business');
Insert school_speciality values(34,5,4.4,'New York University','Business');
Insert school_speciality values(23,6,4.3,'University of Virginia','Business');
Insert school_speciality values(22,7,4.2,'Carnegie Mellon University','Business');
Insert school_speciality values(28,7,4.2,'University of North Carolina-Chapel Hill','Business');
Insert school_speciality values(45,7,4.2,'University of Texas-Austin','Business');
Insert school_speciality values(13,10,4.1,'Cornell University','Business');
Insert school_speciality values(75,10,4.1,'Indiana University-Bloomington','Business');
Insert school_speciality values(20,10,4.1,'University of Notre Dame','Business');
Insert school_speciality values(27,10,4.1,'University of Southern California','Business');
Insert school_speciality values(12,14,4.0,'Washington University in St. Louis','Business');
Insert school_speciality values(18,15,3.9,'Emory University','Business');
Insert school_speciality values(24,15,3.9,'Georgetown University','Business');
Insert school_speciality values(40,15,3.9,'University of Illinois—Urbana-Champaign','Business');
Insert school_speciality values(74,15,3.9,'University of Minnesota-Twin Cities','Business');
Insert school_speciality values(38,15,3.9,'University of Wisconsin-Madison','Business');
Insert school_speciality values(58,21,3.8,'Ohio State University-Columbus','Business');
Insert school_speciality values(48,22,3.7,'Pennsylvania State University-University Park','Business');
Insert school_speciality values(66,22,3.7,'Purdue University-West Lafayette','Business');
Insert school_speciality values(105,22,3.7,'University of Arizona','Business');
Insert school_speciality values(56,22,3.7,'University of Maryland-College Park','Business');
Insert school_speciality values(42,22,3.7,'University of Washington','Business');
Insert school_speciality values(127,29,3.6,'Arizona State University-Tempe','Business');
Insert school_speciality values(10000,29,3.6,'Babson College','Business');
Insert school_speciality values(36,29,3.6,'Georgia Institute of Technology','Business');
Insert school_speciality values(62,29,3.6,'Texas A&M University-College Station','Business');
Insert school_speciality values(49,29,3.6,'University of Florida','Business');
Insert school_speciality values(60,29,3.6,'University of Georgia','Business');
Insert school_speciality values(79,34,3.5,'Brigham Young University-Provo','Business');
Insert school_speciality values(47,34,3.5,'University of California-Irvine','Business');
Insert school_speciality values(80,34,3.5,'University of Colorado-Boulder','Business');
Insert school_speciality values(64,34,3.5,'University of Iowa','Business');
Insert school_speciality values(30,34,3.5,'Wake Forest University','Business');
Insert school_speciality values(57,39,3.4,'Boston University','Business');
Insert school_speciality values(41,39,3.4,'Case Western Reserve University','Business');
Insert school_speciality values(33,39,3.4,'College of William and Mary','Business');
Insert school_speciality values(61,39,3.4,'University of Pittsburgh','Business');
Insert school_speciality values(54,43,3.3,'George Washington University','Business');
Insert school_speciality values(67,43,3.3,'Southern Methodist University','Business');
Insert school_speciality values(51,43,3.3,'Syracuse University','Business');
Insert school_speciality values(50,43,3.3,'Tulane University','Business');
Insert school_speciality values(126,43,3.3,'University of Arkansas','Business');
Insert school_speciality values(113,43,3.3,'University of South Carolina','Business');
Insert school_speciality values(71,43,3.3,'Virginia Tech','Business');
Insert school_speciality values(142,50,3.2,'Auburn University','Business');
Insert school_speciality values(2002,50,3.2,'Bentley University','Business');
Insert school_speciality values(215,50,3.2,'Georgia State University','Business');
Insert school_speciality values(55,50,3.2,'Pepperdine University','Business');
Insert school_speciality values(39,50,3.2,'University of California-San Diego','Business');
Insert school_speciality values(65,50,3.2,'University of Connecticut','Business');
Insert school_speciality values(96,50,3.2,'University of Massachusetts-Amherst','Business');
Insert school_speciality values(92,50,3.2,'University of Missouri','Business');
Insert school_speciality values(114,50,3.2,'University of Oregon','Business');
Insert school_speciality values(101,50,3.2,'University of Tennessee','Business');
Insert school_speciality values(132,50,3.2,'University of Utah','Business');
Insert school_speciality values(76,61,3.1,'Baylor University','Business');
Insert school_speciality values(68,61,3.1,'Clemson University','Business');
Insert school_speciality values(2032,61,3.1,'CUNY-Baruch College','Business');
Insert school_speciality values(112,61,3.1,'Florida State University','Business');
Insert school_speciality values(70,61,3.1,'Miami University-Oxford','Business');
Insert school_speciality values(97,61,3.1,'Northeastern University','Business');
Insert school_speciality values(44,61,3.1,'Rensselaer Polytechnic Institute','Business');
Insert school_speciality values(3001,61,3.1,'Santa Clara University','Business');
Insert school_speciality values(129,61,3.1,'Temple University','Business');
Insert school_speciality values(107,61,3.1,'Texas Christian University','Business');
Insert school_speciality values(1030,61,3.1,'United States Air Force Academy','Business');
Insert school_speciality values(93,61,3.1,'University of Alabama','Business');
Insert school_speciality values(85,61,3.1,'University of Kansas','Business');
Insert school_speciality values(120,61,3.1,'University of Kentucky','Business');
Insert school_speciality values(52,61,3.1,'University of Miami','Business');
Insert school_speciality values(95,61,3.1,'University of Nebraska-Lincon','Business');
Insert school_speciality values(110,61,3.1,'University of Oklahoma','Business');
Insert school_speciality values(1033,61,3.1,'University of Richmond','Business');
Insert school_speciality values(2000,61,3.1,'Villanova University','Business');
Insert school_speciality values(87,80,3.0,'American University','Business');
Insert school_speciality values(133,80,3.0,'DePaul University','Business');
Insert school_speciality values(69,80,3.0,'Fordham University','Business');
Insert school_speciality values(139,80,3.0,'George Mason University','Business');
Insert school_speciality values(86,80,3.0,'Iowa State University','Business');
Insert school_speciality values(138,80,3.0,'Louisiana State University-Baton Rouge','Business');
Insert school_speciality values(111,80,3.0,'Loyola University Chicago','Business');
Insert school_speciality values(118,80,3.0,'University at Buffalo-SUNY','Business');
Insert school_speciality values(103,80,3.0,'University of California-Riverside','Business');
Insert school_speciality values(73,80,3.0,'University of Delaware','Business');
Insert school_speciality values(88,80,3.0,'University of Denver','Business');
Insert school_speciality values(136,80,3.0,'University of Illinois-Chicago','Business');
Insert school_speciality values(172,80,3.0,'University of Louisville','Business');
Insert school_speciality values(32,93,2.9,'Brandeis University','Business');
Insert school_speciality values(125,93,2.9,'Colorado State University','Business');
Insert school_speciality values(108,93,2.9,'Drexel University','Business');
Insert school_speciality values(3003,93,2.9,'Gonzaga University','Business');
Insert school_speciality values(31,93,2.9,'Lehigh University','Business');
Insert school_speciality values(3002,93,2.9,'Loyola Marymount University','Business');
Insert school_speciality values(84,93,2.9,'Marquette University','Business');
Insert school_speciality values(89,93,2.9,'North Carolina State University-Raleigh','Business');
Insert school_speciality values(150,93,2.9,'Oklahoma State University','Business');
Insert school_speciality values(2006,93,2.9,'Rochester Institute of Technology','Business');
Insert school_speciality values(59,93,2.9,'Rutgers, the State University of New Jersey-New Brunswick','Business');
Insert school_speciality values(83,93,2.9,'Saint Louis University','Business');
Insert school_speciality values(151,93,2.9,'San Diego State University','Business');
Insert school_speciality values(3005,93,2.9,'Seattle University','Business');
Insert school_speciality values(2014,93,2.9,'St. Joseph-s University','Business');
Insert school_speciality values(169,93,2.9,'Texas Tech University','Business');
Insert school_speciality values(203,93,2.9,'University of Colorado-Denver','Business');
Insert school_speciality values(189,93,2.9,'University of Houston','Business');
Insert school_speciality values(146,93,2.9,'University of Mississippi','Business');
Insert school_speciality values(147,93,2.9,'University of Texas-Dallas','Business');
Insert school_speciality values(19,93,2.9,'Washington State University','Business');
Insert school_speciality values(4000,114,2.8,'Creighton University','Business');
Insert school_speciality values(123,114,2.8,'Kansas State University','Business');
Insert school_speciality values(116,114,2.8,'Ohio University','Business');
Insert school_speciality values(143,114,2.8,'Oregon State University','Business');
Insert school_speciality values(144,114,2.8,'Rutgers, The State University of New Jersey-Newark','Business');
Insert school_speciality values(137,114,2.8,'University at Albany-SUNY','Business');
Insert school_speciality values(152,114,2.8,'University of Alabama-Birmingham','Business');
Insert school_speciality values(145,114,2.8,'University of Cincinnati','Business');
Insert school_speciality values(249,114,2.8,'University of Memphis','Business');
Insert school_speciality values(182,114,2.8,'University of New Mexico','Business');
Insert school_speciality values(198,114,2.8,'University of North Carolina-Charlotte','Business');
Insert school_speciality values(106,114,2.8,'University of San Diego','Business');
Insert school_speciality values(141,114,2.8,'University of San Francisco','Business');
Insert school_speciality values(264,114,2.8,'University of Wisconsin-Milwaukee','Business');
Insert school_speciality values(159,114,2.8,'Virginia Commonwealth University','Business');
Insert school_speciality values(1016,114,2.8,'Washington and Lee University','Business');
Insert school_speciality values(168,131,2.7,'Ball State University','Business');
Insert school_speciality values(82,131,2.7,'SUNY-Binghamton','Business');
Insert school_speciality values(1031,131,2.7,'Bucknell University','Business');
Insert school_speciality values(4001,131,2.7,'Butler University','Business');
Insert school_speciality values(3009,131,2.7,'​California Polytechnic State University-San Luis Obispo','Business');
Insert school_speciality values(140,131,2.7,'Hofstra University','Business');
Insert school_speciality values(5072,131,2.7,'Kennesaw State University','Business');
Insert school_speciality values(2004,131,2.7,'Loyola University Maryland','Business');
Insert school_speciality values(227,131,2.7,'Northern Illinois University','Business');
Insert school_speciality values(5001,131,2.7,'Rollins College','Business');
Insert school_speciality values(2038,131,2.7,'Rutgers, The State University of New Jersey-Camden','Business');
Insert school_speciality values(3040,131,2.7,'San Jose State University','Business');
Insert school_speciality values(134,131,2.7,'Seton Hall University','Business');
Insert school_speciality values(6000,131,2.7,'United States Coast Guard Academy','Business');
Insert school_speciality values(170,131,2.7,'University of Central Florida','Business');
Insert school_speciality values(3046,131,2.7,'University of Colorado-Colorado Springs','Business');
Insert school_speciality values(166,131,2.7,'University of Hawaii-Manoa','Business');
Insert school_speciality values(171,131,2.7,'University of Idaho','Business');
Insert school_speciality values(250,131,2.7,'University of Missouri-St. Louis','Business');
Insert school_speciality values(251,131,2.7,'University of Montana','Business');
Insert school_speciality values(252,131,2.7,'University of Nebraska-Omaha','Business');
Insert school_speciality values(167,131,2.7,'University of Rhode Island','Business');
Insert school_speciality values(259,131,2.7,'University of Texas-Arlington','Business');
Insert school_speciality values(98,131,2.7,'University of Vermont','Business');
Insert school_speciality values(4005,131,2.7,'Xavier University','Business');
Insert school_speciality values(3060,156,2.6,'Boise State University','Business');
Insert school_speciality values(185,156,2.6,'Bowling Green State University','Business');
Insert school_speciality values(4003,156,2.6,'Bradley University','Business');
Insert school_speciality values(3030,156,2.6,'California State Polytechnic University-Pomona','Business');
Insert school_speciality values(3036,156,2.6,'California State University-Fullerton','Business');
Insert school_speciality values(3062,156,2.6,'California State University-Los Angeles','Business');
Insert school_speciality values(3006,156,2.6,'Chapman University','Business');
Insert school_speciality values(91,156,2.6,'Clark University','Business');
Insert school_speciality values(4002,156,2.6,'Drake University','Business');
Insert school_speciality values(5000,156,2.6,'Elon University','Business');
Insert school_speciality values(2005,156,2.6,'Fairfield University','Business');
Insert school_speciality values(102,156,2.6,'Howard University','Business');
Insert school_speciality values(178,156,2.6,'Kent State University','Business');
Insert school_speciality values(165,156,2.6,'Mississippi State University','Business');
Insert school_speciality values(232,156,2.6,'Portland State University','Business');
Insert school_speciality values(2011,156,2.6,'Quinnipiac University','Business');
Insert school_speciality values(154,156,2.6,'Southern Illinois University-Carbondale','Business');
Insert school_speciality values(1080,156,2.6,'St. John-s University','Business');
Insert school_speciality values(188,156,2.6,'University of Alabama-Huntsville','Business');
Insert school_speciality values(246,156,2.6,'University of Arkansas-Little Rock','Business');
Insert school_speciality values(2123,156,2.6,'University of Baltimore','Business');
Insert school_speciality values(115,156,2.6,'University of Dayton','Business');
Insert school_speciality values(173,156,2.6,'University of Maine','Business');
Insert school_speciality values(248,156,2.6,'University of Massachusetts-Boston','Business');
Insert school_speciality values(4040,156,2.6,'University of Minnesota-Duluth','Business');
Insert school_speciality values(197,156,2.6,'University of Missouri-Kansas City','Business');
Insert school_speciality values(253,156,2.6,'University of Nevada-Las Vegas','Business');
Insert school_speciality values(191,156,2.6,'University of North Carolina-Greensboro','Business');
Insert school_speciality values(3007,156,2.6,'University of Portland','Business');
Insert school_speciality values(131,156,2.6,'University of St. Thomas','Business');
Insert school_speciality values(94,156,2.6,'University of Tulsa','Business');
Insert school_speciality values(174,156,2.6,'University of Wyoming','Business');
Insert school_speciality values(265,156,2.6,'Utah State University','Business');
Insert school_speciality values(179,156,2.6,'West Virginia University','Business');
Insert school_speciality values(63,156,2.6,'Worcester Polytechnic Institute','Business');
Insert school_speciality values(2010,191,2.5,'Bryant University','Business');
Insert school_speciality values(5002,191,2.5,'The Citadel','Business');
Insert school_speciality values(130,191,2.5,'Duquesne University','Business');
Insert school_speciality values(213,191,2.5,'Florida International University','Business');
Insert school_speciality values(5028,191,2.5,'Georgia College & State University','Business');
Insert school_speciality values(274,191,2.5,'Idaho State University','Business');
Insert school_speciality values(2008,191,2.5,'Ithaca College','Business');
Insert school_speciality values(4006,191,2.5,'John Carroll University','Business');
Insert school_speciality values(5012,191,2.5,'Loyola University New Orleans','Business');
Insert school_speciality values(202,191,2.5,'New Mexico State University','Business');
Insert school_speciality values(226,191,2.5,'Northern Arizona University','Business');
Insert school_speciality values(230,191,2.5,'Old Dominion University','Business');
Insert school_speciality values(180,191,2.5,'Pace University','Business');
Insert school_speciality values(2001,191,2.5,'Providence College','Business');
Insert school_speciality values(3066,191,2.5,'San Francisco State University','Business');
Insert school_speciality values(4043,191,2.5,'University of Illinois-Springfield','Business');
Insert school_speciality values(2087,191,2.5,'University of Massachusetts-Dartmouth','Business');
Insert school_speciality values(157,191,2.5,'University of Massachusetts-Lowell','Business');
Insert school_speciality values(4039,191,2.5,'University of Michigan-Dearborn','Business');
Insert school_speciality values(109,191,2.5,'University of New Hampshire','Business');
Insert school_speciality values(5017,191,2.5,'University of North Carolina-Wilmington','Business');
Insert school_speciality values(256,191,2.5,'University of North Texas','Business');
Insert school_speciality values(158,191,2.5,'University of South Florida','Business');
Insert school_speciality values(5060,191,2.5,'University of Tennessee-Chattanooga','Business');
Insert school_speciality values(261,191,2.5,'University of Texas-San Antonio','Business');
Insert school_speciality values(4004,191,2.5,'Valparaiso University','Business');
Insert school_speciality values(266,191,2.5,'Wayne State University','Business');
Insert school_speciality values(192,191,2.5,'Western Michigan University','Business');
Insert school_speciality values(267,191,2.5,'Wichita State University','Business');
Insert school_speciality values(5010,222,2.4,'Appalachian State University','Business');
Insert school_speciality values(5005,222,2.4,'Belmont University','Business');
Insert school_speciality values(3051,222,2.4,'California State University-Fresno','Business');
Insert school_speciality values(3031,222,2.4,'California State University-Long Beach','Business');
Insert school_speciality values(3069,222,2.4,'California State University-Northridge','Business');
Insert school_speciality values(124,222,2.4,'Clarkson University','Business');
Insert school_speciality values(5011,222,2.4,'College of Charleston','Business');
Insert school_speciality values(2084,222,2.4,'Fairleigh Dickinson University','Business');
Insert school_speciality values(212,222,2.4,'Florida Atlantic University','Business');
Insert school_speciality values(214,222,2.4,'Georgia Southern University','Business');
Insert school_speciality values(100,222,2.4,'Illinois Institute of Technology','Business');
Insert school_speciality values(149,222,2.4,'Illinois State University','Business');
Insert school_speciality values(216,222,2.4,'Indiana State University','Business');
Insert school_speciality values(4126,222,2.4,'Indiana University-Purdue University-Fort Wayne','Business');
Insert school_speciality values(2025,222,2.4,'La Salle University','Business');
Insert school_speciality values(5045,222,2.4,'Marshall University','Business');
Insert school_speciality values(222,222,2.4,'Montana State University','Business');
Insert school_speciality values(6073,222,2.4,'Pennsylvania State University-Erie, The Behrend College','Business');
Insert school_speciality values(6074,222,2.4,'Pennsylvania State University—​Harrisburg','Business');
Insert school_speciality values(5004,222,2.4,'Samford University','Business');
Insert school_speciality values(2015,222,2.4,'Simmons College','Business');
Insert school_speciality values(4045,222,2.4,'Southern Illinois University-Edwardsville','Business');
Insert school_speciality values(5006,222,2.4,'Stetson University','Business');
Insert school_speciality values(3008,222,2.4,'St. Mary-s College of California','Business');
Insert school_speciality values(3071,222,2.4,'Texas A&M International University','Business');
Insert school_speciality values(3053,222,2.4,'Texas State University','Business');
Insert school_speciality values(3000,222,2.4,'Trinity University','Business');
Insert school_speciality values(244,222,2.4,'University of Akron','Business');
Insert school_speciality values(3077,222,2.4,'University of Alaska-Anchorage','Business');
Insert school_speciality values(3014,222,2.4,'University of Dallas','Business');
Insert school_speciality values(4008,222,2.4,'University of Evansville','Business');
Insert school_speciality values(190,222,2.4,'University of Nevada-Reno','Business');
Insert school_speciality values(254,222,2.4,'University of New Orleans','Business');
Insert school_speciality values(183,222,2.4,'University of North Dakota','Business');
Insert school_speciality values(255,222,2.4,'University of Northern Colorado','Business');
Insert school_speciality values(4019,222,2.4,'University of Northern Iowa','Business');
Insert school_speciality values(2007,222,2.4,'University of Scranton','Business');
Insert school_speciality values(5023,222,2.4,'University of Tampa','Business');
Insert school_speciality values(104,222,2.4,'University of the Pacific','Business');
Insert school_speciality values(4052,222,2.4,'University of Wisconsin-Whitewater','Business');
Insert school_speciality values(1087,222,2.4,'Virginia Military Institute','Business');
Insert school_speciality values(5101,263,2.3,'Auburn University-Montgomery','Business');
Insert school_speciality values(3042,263,2.3,'California State University-Chico','Business');
Insert school_speciality values(3064,263,2.3,'California State University-Sacramento','Business');
Insert school_speciality values(2033,263,2.3,'Canisius College','Business');
Insert school_speciality values(194,263,2.3,'Central Michigan University','Business');
Insert school_speciality values(209,263,2.3,'Cleveland State University','Business');
Insert school_speciality values(195,263,2.3,'East Carolina University','Business');
Insert school_speciality values(4085,263,2.3,'Eastern Michigan University','Business');
Insert school_speciality values(4128,263,2.3,'Indiana University-South Bend','Business');
Insert school_speciality values(201,263,2.3,'Louisiana Tech University','Business');
Insert school_speciality values(2012,263,2.3,'Marist College','Business');
Insert school_speciality values(5008,263,2.3,'Mercer University','Business');
Insert school_speciality values(3104,263,2.3,'Montana State University-Billings','Business');
Insert school_speciality values(1149,263,2.3,'Morehouse College','Business');
Insert school_speciality values(122,263,2.3,'New Jersey Institute of Technology','Business');
Insert school_speciality values(186,263,2.3,'North Dakota State University','Business');
Insert school_speciality values(5082,263,2.3,'Northern Kentucky University','Business');
Insert school_speciality values(4018,263,2.3,'Rockhurst University','Business');
Insert school_speciality values(2061,263,2.3,'Suffolk University','Business');
Insert school_speciality values(2013,263,2.3,'SUNY-Geneseo','Business');
Insert school_speciality values(2056,263,2.3,'Towson University','Business');
Insert school_speciality values(4007,263,2.3,'Truman State University','Business');
Insert school_speciality values(245,263,2.3,'University of Alaska-Fairbanks','Business');
Insert school_speciality values(1224,263,2.3,'University of Hawaii-Hilo','Business');
Insert school_speciality values(9017,263,2.3,'University of South Carolina-Aiken','Business');
Insert school_speciality values(184,263,2.3,'University of South Dakota','Business');
Insert school_speciality values(262,263,2.3,'University of Toledo','Business');
Insert school_speciality values(4034,263,2.3,'University of Wisconsin-Eau Claire','Business');
Insert school_speciality values(4029,263,2.3,'University of Wisconsin-​La Crosse','Business');
Insert school_speciality values(3078,263,2.3,'Weber State University','Business');
Insert school_speciality values(3032,263,2.3,'Western Washington University','Business');
Insert school_speciality values(268,263,2.3,'Wright State University','Business');
Insert school_speciality values(5053,299,2.2,'Arkansas State University','Business');
Insert school_speciality values(3052,299,2.2,'Central Washington University','Business');
Insert school_speciality values(5063,299,2.2,'Coastal Carolina University','Business');
Insert school_speciality values(2003,299,2.2,'College of New Jersey','Business');
Insert school_speciality values(4026,299,2.2,'Grand Valley State University','Business');
Insert school_speciality values(217,299,2.2,'Indiana University of Pennsylvania','Business');
Insert school_speciality values(2078,299,2.2,'Iona College','Business');
Insert school_speciality values(2019,299,2.2,'Le Moyne College','Business');
Insert school_speciality values(5112,299,2.2,'Louisiana State University-Shreveport','Business');
Insert school_speciality values(128,299,2.2,'Michigan Technological University','Business');
Insert school_speciality values(221,299,2.2,'Middle Tennessee State University','Business');
Insert school_speciality values(1094,299,2.2,'Millsaps College','Business');
Insert school_speciality values(4077,299,2.2,'Minnesota State University-Mankato','Business');
Insert school_speciality values(4065,299,2.2,'Missouri State University','Business');
Insert school_speciality values(2036,299,2.2,'Monmouth University','Business');
Insert school_speciality values(2034,299,2.2,'Montclair State University','Business');
Insert school_speciality values(5030,299,2.2,'Murray State University','Business');
Insert school_speciality values(229,299,2.2,'Oakland University','Business');
Insert school_speciality values(3013,299,2.2,'Pacific Lutheran University','Business');
Insert school_speciality values(5020,299,2.2,'Queens University of Charlotte','Business');
Insert school_speciality values(2022,299,2.2,'Rider University','Business');
Insert school_speciality values(3018,299,2.2,'Seattle Pacific University','Business');
Insert school_speciality values(3047,299,2.2,'Sonoma State University','Business');
Insert school_speciality values(2023,299,2.2,'St. Bonaventure University','Business');
Insert school_speciality values(4102,299,2.2,'St. Cloud State University','Business');
Insert school_speciality values(148,299,2.2,'St. John Fisher College','Business');
Insert school_speciality values(3021,299,2.2,'St. Mary-s University of San Antonio','Business');
Insert school_speciality values(238,299,2.2,'Texas A&M University-Corpus Christi','Business');
Insert school_speciality values(3081,299,2.2,'University of Houston-​Clear Lake','Business');
Insert school_speciality values(247,299,2.2,'University of Louisiana-​Lafayette','Business');
Insert school_speciality values(258,299,2.2,'University of Southern Mississippi','Business');
Insert school_speciality values(5059,299,2.2,'University of South Florida-St. Petersburg','Business');
Insert school_speciality values(5052,299,2.2,'University of Tennessee-Martin','Business');
Insert school_speciality values(260,299,2.2,'University of Texas-El Paso','Business');
Insert school_speciality values(4081,299,2.2,'University of Wisconsin-Oshkosh','Business');
Insert school_speciality values(5034,299,2.2,'Western Carolina University','Business');
Insert school_speciality values(4048,299,2.2,'Western Illinois University','Business');
Insert school_speciality values(5031,299,2.2,'Western Kentucky University','Business');
Insert school_speciality values(153,337,2.1,'Adelphi University','Business');
Insert school_speciality values(1126,337,2.1,'Berry College','Business');
Insert school_speciality values(3068,337,2.1,'California State University-Bakersfield','Business');
Insert school_speciality values(3093,337,2.1,'California State University-East Bay','Business');
Insert school_speciality values(3082,337,2.1,'California State University-San Bernardino','Business');
Insert school_speciality values(2057,337,2.1,'College at Brockport-SUNY','Business');
Insert school_speciality values(3096,337,2.1,'Colorado State University-Pueblo','Business');
Insert school_speciality values(2126,337,2.1,'Delaware State University','Business');
Insert school_speciality values(4030,337,2.1,'Eastern Illinois University','Business');
Insert school_speciality values(5076,337,2.1,'Eastern Kentucky University','Business');
Insert school_speciality values(3065,337,2.1,'Eastern Washington University','Business');
Insert school_speciality values(210,337,2.1,'East Tennessee State University','Business');
Insert school_speciality values(5080,337,2.1,'Florida Gulf Coast University','Business');
Insert school_speciality values(8084,337,2.1,'Indiana University-Kokomo','Business');
Insert school_speciality values(5065,337,2.1,'Jacksonville University','Business');
Insert school_speciality values(219,337,2.1,'Lamar University','Business');
Insert school_speciality values(4110,337,2.1,'Minnesota State University-Moorhead','Business');
Insert school_speciality values(8105,337,2.1,'Missouri Western State University','Business');
Insert school_speciality values(5062,337,2.1,'Morehead State University','Business');
Insert school_speciality values(2050,337,2.1,'Niagara University','Business');
Insert school_speciality values(4087,337,2.1,'Northern Michigan University','Business');
Insert school_speciality values(8002,337,2.1,'Ohio Northern University','Business');
Insert school_speciality values(4089,337,2.1,'Pittsburg State University','Business');
Insert school_speciality values(2068,337,2.1,'Robert Morris University-PA','Business');
Insert school_speciality values(2037,337,2.1,'Roger Williams University','Business');
Insert school_speciality values(2020,337,2.1,'Rowan University','Business');
Insert school_speciality values(2044,337,2.1,'Sacred Heart University','Business');
Insert school_speciality values(2071,337,2.1,'Salisbury University','Business');
Insert school_speciality values(234,337,2.1,'Sam Houston State University','Business');
Insert school_speciality values(2093,337,2.1,'Shippensburg University of Pennsylvania','Business');
Insert school_speciality values(1113,337,2.1,'Siena College','Business');
Insert school_speciality values(4094,337,2.1,'Southeast Missouri State University','Business');
Insert school_speciality values(3070,337,2.1,'Southern Utah University','Business');
Insert school_speciality values(3088,337,2.1,'Stephen F. Austin State University','Business');
Insert school_speciality values(4046,337,2.1,'St. Xavier University','Business');
Insert school_speciality values(2051,337,2.1,'SUNY College-Oneonta','Business');
Insert school_speciality values(2024,337,2.1,'SUNY-New Paltz','Business');
Insert school_speciality values(2063,337,2.1,'​SUNY-Oswego','Business');
Insert school_speciality values(237,337,2.1,'Texas A&M University-Commerce','Business');
Insert school_speciality values(9009,337,2.1,'Tuskegee University','Business');
Insert school_speciality values(4079,337,2.1,'University of Central Missouri','Business');
Insert school_speciality values(4025,337,2.1,'University of Detroit Mercy','Business');
Insert school_speciality values(7030,337,2.1,'University of Houston-Downtown','Business');
Insert school_speciality values(257,337,2.1,'University of South Alabama','Business');
Insert school_speciality values(9033,337,2.1,'University of South Carolina-Upstate','Business');
Insert school_speciality values(4146,337,2.1,'University of Southern Indiana','Business');
Insert school_speciality values(5092,337,2.1,'University of West Georgia','Business');
Insert school_speciality values(1229,337,2.1,'University of Wisconsin-Parkside','Business');
Insert school_speciality values(4072,337,2.1,'University of Wisconsin-River Falls','Business');
Insert school_speciality values(5079,337,2.1,'Valdosta State University','Business');
Insert school_speciality values(5126,337,2.1,'Virginia State University','Business');
Insert school_speciality values(4097,337,2.1,'Washburn University','Business');
Insert school_speciality values(2104,337,2.1,'William Paterson University of New Jersey','Business');
Insert school_speciality values(5026,337,2.1,'Winthrop University','Business');
Insert school_speciality values(4149,337,2.1,'Youngstown State University','Business');
Insert school_speciality values(3016,393,2.0,'Abilene Christian University','Business');
Insert school_speciality values(204,393,2.0,'Barry University','Business');
Insert school_speciality values(5013,393,2.0,'Bellarmine University','Business');
Insert school_speciality values(2103,393,2.0,'Bloomsburg University of Pennsylvania','Business');
Insert school_speciality values(3056,393,2.0,'California State University-Stanislaus','Business');
Insert school_speciality values(5014,393,2.0,'Christopher Newport University','Business');
Insert school_speciality values(2145,393,2.0,'Clarion University of Pennsylvania','Business');
Insert school_speciality values(5103,393,2.0,'Columbus State University','Business');
Insert school_speciality values(4104,393,2.0,'Emporia State University','Business');
Insert school_speciality values(4125,393,2.0,'Indiana University Northwest','Business');
Insert school_speciality values(2054,393,2.0,'King-s College','Business');
Insert school_speciality values(5029,393,2.0,'Longwood University','Business');
Insert school_speciality values(2016,393,2.0,'Manhattan College','Business');
Insert school_speciality values(7008,393,2.0,'Menlo College','Business');
Insert school_speciality values(223,393,2.0,'Morgan State University','Business');
Insert school_speciality values(225,393,2.0,'North Carolina A&T State University','Business');
Insert school_speciality values(3023,393,2.0,'Oklahoma City University','Business');
Insert school_speciality values(2026,393,2.0,'Ramapo College of New Jersey','Business');
Insert school_speciality values(4142,393,2.0,'Saginaw Valley State University','Business');
Insert school_speciality values(5043,393,2.0,'Shenandoah University','Business');
Insert school_speciality values(2077,393,2.0,'SUNY-Plattsburgh','Business');
Insert school_speciality values(2122,393,2.0,'SUNY Polytechnic Institute','Business');
Insert school_speciality values(1123,393,2.0,'Susquehanna University','Business');
Insert school_speciality values(236,393,2.0,'Tennessee State University','Business');
Insert school_speciality values(5036,393,2.0,'Tennessee Technological University','Business');
Insert school_speciality values(240,393,2.0,'Texas Southern University','Business');
Insert school_speciality values(3048,393,2.0,'Texas Wesleyan University','Business');
Insert school_speciality values(5070,393,2.0,'University of Central Arkansas','Business');
Insert school_speciality values(3125,393,2.0,'University of Houston-Victoria','Business');
Insert school_speciality values(5096,393,2.0,'University of Louisiana-Monroe','Business');
Insert school_speciality values(2179,393,2.0,'University of Maryland-Eastern Shore','Business');
Insert school_speciality values(5057,393,2.0,'University of North Georgia','Business');
Insert school_speciality values(2180,393,2.0,'University of Southern Maine','Business');
Insert school_speciality values(3029,393,2.0,'University of St. Thomas','Business');
Insert school_speciality values(3075,393,2.0,'University of Texas-Tyler','Business');
Insert school_speciality values(263,393,2.0,'University of West Florida','Business');
Insert school_speciality values(7039,393,2.0,'Utah Valley University','Business');
Insert school_speciality values(193,393,2.0,'Widener University','Business');
Insert school_speciality values(208,432,1.9,'Clark Atlanta University','Business');
Insert school_speciality values(4021,432,1.9,'Dominican University','Business');
Insert school_speciality values(4011,432,1.9,'Drury University','Business');
Insert school_speciality values(1196,432,1.9,'Fort Lewis College','Business');
Insert school_speciality values(5077,432,1.9,'Francis Marion University','Business');
Insert school_speciality values(2127,432,1.9,'Frostburg State University','Business');
Insert school_speciality values(5109,432,1.9,'Grambling State University','Business');
Insert school_speciality values(5110,432,1.9,'Jacksonville State University','Business');
Insert school_speciality values(2164,432,1.9,'LIU Post','Business');
Insert school_speciality values(5089,432,1.9,'McNeese State University','Business');
Insert school_speciality values(9004,432,1.9,'Meredith College','Business');
Insert school_speciality values(117,432,1.9,'Missouri University of Science & Technology','Business');
Insert school_speciality values(5114,432,1.9,'Norfolk State University','Business');
Insert school_speciality values(5066,432,1.9,'North Carolina Central University','Business');
Insert school_speciality values(1217,432,1.9,'Savannah State University','Business');
Insert school_speciality values(1118,432,1.9,'Stonehill College','Business');
Insert school_speciality values(9093,432,1.9,'University of Arkansas-Fort Smith','Business');
Insert school_speciality values(5039,432,1.9,'University of Montevallo','Business');
Insert school_speciality values(3126,432,1.9,'University of Texas of the Permian Basin','Business');
Insert school_speciality values(2072,432,1.9,'West Chester University of Pennsylvania','Business');
Insert school_speciality values(2064,432,1.9,'Western New England University','Business');
Insert school_speciality values(4073,432,1.9,'Winona State University','Business');
Insert school_speciality values(5086,432,1.9,'Winston-​Salem State University','Business');
Insert school_speciality values(5087,455,1.8,'Arkansas Tech University','Business');
Insert school_speciality values(4116,455,1.8,'Black Hills State University','Business');
Insert school_speciality values(9058,455,1.8,'Clayton State University','Business');
Insert school_speciality values(5108,455,1.8,'Georgia Southwestern State University','Business');
Insert school_speciality values(218,455,1.8,'Jackson State University','Business');
Insert school_speciality values(9042,455,1.8,'Lander University','Business');
Insert school_speciality values(5090,455,1.8,'Nicholls State University','Business');
Insert school_speciality values(196,455,1.8,'South Carolina State University','Business');
Insert school_speciality values(5118,455,1.8,'Southeastern Louisiana University','Business');
Insert school_speciality values(3109,455,1.8,'Southeastern Oklahoma State University','Business');
Insert school_speciality values(3128,455,1.8,'West Texas A&M University','Business');
Insert school_speciality values(9101,466,1.7,'Dalton State College','Business');
Insert school_speciality values(5085,466,1.7,'Fayetteville State University','Business');
Insert school_speciality values(9003,466,1.7,'Florida Southern College','Business');
Insert school_speciality values(3103,466,1.7,'Midwestern State University','Business');
Insert school_speciality values(5115,466,1.7,'Northwestern State University of Louisiana','Business');
Insert school_speciality values(3059,466,1.7,'Woodbury University','Business');
Insert school_speciality values(9030,472,1.6,'Elizabeth City State University','Business');
Insert school_speciality values(5088,472,1.6,'Henderson State University','Business');
Insert school_speciality values(1169,472,1.6,'Ouachita Baptist University','Business');
Insert school_speciality values(3107,472,1.6,'Prairie View A&M University','Business');
Insert school_speciality values(5119,472,1.6,'Southern Arkansas University','Business');
Insert school_speciality values(5120,472,1.6,'Southern University and A&M College','Business');
Insert school_speciality values(5121,472,1.6,'Southern University-New Orleans','Business');


Commit;