package com.bedrosians.bedlogic.domain.product;// default package
// Generated Feb 26, 2014 5:50:34 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProdSurfaceStyle generated by hbm2java
 */
@Entity
@Table(name = "prod_surface_style", schema = "public")
public class ProdSurfaceStyle implements java.io.Serializable {

	private String description;

	public ProdSurfaceStyle() {
	}

	public ProdSurfaceStyle(String description) {
		this.description = description;
	}

	@Id
	@Column(name = "description", unique = true, nullable = false, length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
