package com.bedrosians.bedlogic.domain.product;
// Generated Feb 27, 2014 2:40:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdMaterialProductStatus generated by hbm2java
 */
@Entity
@Table(name = "prod_material_product_status", schema = "public")
public class ProdMaterialProductStatus implements java.io.Serializable {

	private String mpsCode;
	private String description;
	private Set products = new HashSet(0);

	public ProdMaterialProductStatus() {
	}

	public ProdMaterialProductStatus(String mpsCode) {
		this.mpsCode = mpsCode;
	}

	public ProdMaterialProductStatus(String mpsCode, String description,
			Set products) {
		this.mpsCode = mpsCode;
		this.description = description;
		this.products = products;
	}

	@Id
	@Column(name = "mps_code", unique = true, nullable = false, length = 10)
	public String getMpsCode() {
		return this.mpsCode;
	}

	public void setMpsCode(String mpsCode) {
		this.mpsCode = mpsCode;
	}

	@Column(name = "description", length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	

	public void setProducts(Set products) {
		this.products = products;
	}

}
