package com.bedrosians.bedlogic.domain.product;
// Generated Feb 27, 2014 2:40:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * ProdNote generated by hbm2java
 */
@Entity
@Table(name = "prod_note", schema = "public")
public class ProdNote implements java.io.Serializable {

	private int noteId;
	private Product product;
	private String type;
	private String note;

	public ProdNote() {
	}

	public ProdNote(int noteId) {
		this.noteId = noteId;
	}

	public ProdNote(int noteId, Product product, String type, String note) {
		this.noteId = noteId;
		this.product = product;
		this.type = type;
		this.note = note;
	}

	@Id
	@Column(name = "note_id", unique = true, nullable = false)
	public int getNoteId() {
		return this.noteId;
	}

	public void setNoteId(int noteId) {
		this.noteId = noteId;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "note", length = 120)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

}
