package com.bedrosians.bedlogic.domain.product;
// Generated Feb 27, 2014 2:40:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdVendorProductLink generated by hbm2java
 */
@Entity
@Table(name = "prod_vendor_product_link", schema = "public")
public class ProdVendorProductLink implements java.io.Serializable {

	private ProdVendorProductLinkId id;
	private ProdVendor prodVendor;
	private Product product;
	private String xrefId;
	private String priceUnit;
	private String fob;
	private BigDecimal cost;
	private BigDecimal discountPct;
	private Boolean priceRoundAccuracy;
	private BigDecimal netPrice;
	private Short leadTime;
	private BigDecimal freightRateCwt;
	private BigDecimal dutyPct;

	public ProdVendorProductLink() {
	}

	public ProdVendorProductLink(ProdVendorProductLinkId id,
			ProdVendor prodVendor, Product product) {
		this.id = id;
		this.prodVendor = prodVendor;
		this.product = product;
	}

	public ProdVendorProductLink(ProdVendorProductLinkId id,
			ProdVendor prodVendor, Product product, String xrefId,
			String priceUnit, String fob, BigDecimal cost,
			BigDecimal discountPct, Boolean priceRoundAccuracy,
			BigDecimal netPrice, Short leadTime, BigDecimal freightRateCwt,
			BigDecimal dutyPct) {
		this.id = id;
		this.prodVendor = prodVendor;
		this.product = product;
		this.xrefId = xrefId;
		this.priceUnit = priceUnit;
		this.fob = fob;
		this.cost = cost;
		this.discountPct = discountPct;
		this.priceRoundAccuracy = priceRoundAccuracy;
		this.netPrice = netPrice;
		this.leadTime = leadTime;
		this.freightRateCwt = freightRateCwt;
		this.dutyPct = dutyPct;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false, length = 20)),
			@AttributeOverride(name = "vendorId", column = @Column(name = "vendor_id", nullable = false, precision = 10, scale = 0)) })
	public ProdVendorProductLinkId getId() {
		return this.id;
	}

	public void setId(ProdVendorProductLinkId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_id", nullable = false, insertable = false, updatable = false)
	public ProdVendor getProdVendor() {
		return this.prodVendor;
	}

	public void setProdVendor(ProdVendor prodVendor) {
		this.prodVendor = prodVendor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "xref_id", length = 60)
	public String getXrefId() {
		return this.xrefId;
	}

	public void setXrefId(String xrefId) {
		this.xrefId = xrefId;
	}

	@Column(name = "price_unit", length = 4)
	public String getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

	@Column(name = "fob", length = 10)
	public String getFob() {
		return this.fob;
	}

	public void setFob(String fob) {
		this.fob = fob;
	}

	@Column(name = "cost", precision = 9, scale = 4)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "discount_pct", precision = 5)
	public BigDecimal getDiscountPct() {
		return this.discountPct;
	}

	public void setDiscountPct(BigDecimal discountPct) {
		this.discountPct = discountPct;
	}

	@Column(name = "price_round_accuracy", precision = 1, scale = 0)
	public Boolean getPriceRoundAccuracy() {
		return this.priceRoundAccuracy;
	}

	public void setPriceRoundAccuracy(Boolean priceRoundAccuracy) {
		this.priceRoundAccuracy = priceRoundAccuracy;
	}

	@Column(name = "net_price", precision = 9, scale = 4)
	public BigDecimal getNetPrice() {
		return this.netPrice;
	}

	public void setNetPrice(BigDecimal netPrice) {
		this.netPrice = netPrice;
	}

	@Column(name = "lead_time", precision = 4, scale = 0)
	public Short getLeadTime() {
		return this.leadTime;
	}

	public void setLeadTime(Short leadTime) {
		this.leadTime = leadTime;
	}

	@Column(name = "freight_rate_cwt", precision = 9, scale = 4)
	public BigDecimal getFreightRateCwt() {
		return this.freightRateCwt;
	}

	public void setFreightRateCwt(BigDecimal freightRateCwt) {
		this.freightRateCwt = freightRateCwt;
	}

	@Column(name = "duty_pct", precision = 7, scale = 4)
	public BigDecimal getDutyPct() {
		return this.dutyPct;
	}

	public void setDutyPct(BigDecimal dutyPct) {
		this.dutyPct = dutyPct;
	}

}
