package com.bedrosians.bedlogic.domain.product;
// Generated Feb 27, 2014 2:40:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ProdApplication generated by hbm2java
 */
@Entity
@Table(name = "prod_application", schema = "public")
public class ProdApplication implements java.io.Serializable {

	private String productId;
	private Product product;
	private String residential;
	private String lightCommercial;
	private String commercial;

	public ProdApplication() {
	}

	public ProdApplication(Product product) {
		this.product = product;
	}

	public ProdApplication(Product product, String residential,
			String lightCommercial, String commercial) {
		this.product = product;
		this.residential = residential;
		this.lightCommercial = lightCommercial;
		this.commercial = commercial;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "product"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "product_id", unique = true, nullable = false, length = 20)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	public Product getProduct() {
		return this.product;
	}
	

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "residential", length = 20)
	public String getResidential() {
		return this.residential;
	}

	public void setResidential(String residential) {
		this.residential = residential;
	}

	@Column(name = "light_commercial", length = 20)
	public String getLightCommercial() {
		return this.lightCommercial;
	}

	public void setLightCommercial(String lightCommercial) {
		this.lightCommercial = lightCommercial;
	}

	@Column(name = "commercial", length = 20)
	public String getCommercial() {
		return this.commercial;
	}

	public void setCommercial(String commercial) {
		this.commercial = commercial;
	}
		

	@Override
	public String toString() {
		return "ProdApplication ["
				+ "productId=" + productId + 
				", residential=" + residential + 
				", lightCommercial=" + lightCommercial
				+ ", commercial=" + commercial + "]";
	}

	
	
}
