package com.bedrosians.bedlogic.domain.product;
// Generated Feb 27, 2014 2:40:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProdPrice generated by hbm2java
 */
@Entity
@Table(name = "prod_price", schema = "public")
public class ProdPrice implements java.io.Serializable {

	private int priceId;
	private Product product;
	private String type;
	private BigDecimal mbrp;
	private Date dateFrom;
	private Date dateThru;

	public ProdPrice() {
	}

	public ProdPrice(int priceId) {
		this.priceId = priceId;
	}

	public ProdPrice(int priceId, Product product, String type,
			BigDecimal mbrp, Date dateFrom, Date dateThru) {
		this.priceId = priceId;
		this.product = product;
		this.type = type;
		this.mbrp = mbrp;
		this.dateFrom = dateFrom;
		this.dateThru = dateThru;
	}

	@Id
	@Column(name = "price_id", unique = true, nullable = false)
	public int getPriceId() {
		return this.priceId;
	}

	public void setPriceId(int priceId) {
		this.priceId = priceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "mbrp", precision = 9, scale = 4)
	public BigDecimal getMbrp() {
		return this.mbrp;
	}

	public void setMbrp(BigDecimal mbrp) {
		this.mbrp = mbrp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_from", length = 13)
	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_thru", length = 13)
	public Date getDateThru() {
		return this.dateThru;
	}

	public void setDateThru(Date dateThru) {
		this.dateThru = dateThru;
	}

}
