package com.bedrosians.bedlogic.domain.product;
// Generated Feb 27, 2014 2:40:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProdShadeVariation generated by hbm2java
 */
@Entity
@Table(name = "prod_shade_variation", schema = "public")
public class ProdShadeVariation implements java.io.Serializable {

	private String code;
	private String description;

	public ProdShadeVariation() {
	}

	public ProdShadeVariation(String code) {
		this.code = code;
	}

	public ProdShadeVariation(String code, String description) {
		this.code = code;
		this.description = description;
	}

	@Id
	@Column(name = "code", unique = true, nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
