package com.bedrosians.bedlogic.domain.product;
// Generated Feb 27, 2014 2:40:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdVendorProductLinkId generated by hbm2java
 */
@Embeddable
public class ProdVendorProductLinkId implements java.io.Serializable {

	private String productId;
	private long vendorId;

	public ProdVendorProductLinkId() {
	}

	public ProdVendorProductLinkId(String productId, long vendorId) {
		this.productId = productId;
		this.vendorId = vendorId;
	}

	@Column(name = "product_id", nullable = false, length = 20)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "vendor_id", nullable = false, precision = 10, scale = 0)
	public long getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(long vendorId) {
		this.vendorId = vendorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdVendorProductLinkId))
			return false;
		ProdVendorProductLinkId castOther = (ProdVendorProductLinkId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this
				.getProductId() != null && castOther.getProductId() != null && this
				.getProductId().equals(castOther.getProductId())))
				&& (this.getVendorId() == castOther.getVendorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + (int) this.getVendorId();
		return result;
	}

}
