package com.bedrosians.bedlogic.domain.product;
// Generated Feb 27, 2014 2:40:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdVendor generated by hbm2java
 */
@Entity
@Table(name = "prod_vendor", schema = "public")
public class ProdVendor implements java.io.Serializable {

	private long vendorId;
	private String name;
	private String name2;
	private Set<ProdVendorProductLink> prodVendorProductLinks = new HashSet(0);

	public ProdVendor() {
	}

	public ProdVendor(long vendorId) {
		this.vendorId = vendorId;
	}

	public ProdVendor(long vendorId, String name, String name2,
			Set prodVendorProductLinks) {
		this.vendorId = vendorId;
		this.name = name;
		this.name2 = name2;
		this.prodVendorProductLinks = prodVendorProductLinks;
	}

	@Id
	@Column(name = "vendor_id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(long vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "name2", length = 60)
	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodVendor")
	public Set<ProdVendorProductLink> getProdVendorProductLinks() {
		return this.prodVendorProductLinks;
	}

	public void setProdVendorProductLinks(Set<ProdVendorProductLink> prodVendorProductLinks) {
		this.prodVendorProductLinks = prodVendorProductLinks;
	}

}
