package com.collegesearch.domain.school;

// Generated Aug 10, 2015 3:42:22 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrincetonReviewGreatSchoolMajor generated by hbm2java
 */
@Entity
@Table(name = "princeton_review_great_school_major", catalog = "School")
public class PrincetonReviewGreatSchoolMajor implements java.io.Serializable {

	private static final long serialVersionUID = -85490758703320L;
	private PrincetonReviewGreatSchoolMajorId id;
	private String goodAt;

	public PrincetonReviewGreatSchoolMajor() {
	}

	public PrincetonReviewGreatSchoolMajor(PrincetonReviewGreatSchoolMajorId id) {
		this.id = id;
	}

	public PrincetonReviewGreatSchoolMajor(PrincetonReviewGreatSchoolMajorId id, String goodAt) {
		this.id = id;
		this.goodAt = goodAt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schoolId", column = @Column(name = "School_Id", nullable = false)),
			@AttributeOverride(name = "majorId", column = @Column(name = "Major_Id", nullable = false)) })
	public PrincetonReviewGreatSchoolMajorId getId() {
		return this.id;
	}

	public void setId(PrincetonReviewGreatSchoolMajorId id) {
		this.id = id;
	}

	@Column(name = "Good_At", length = 6)
	public String getGoodAt() {
		return this.goodAt;
	}

	public void setGoodAt(String goodAt) {
		this.goodAt = goodAt;
	}

}
