package com.collegesearch.domain.school;

// Generated Aug 10, 2015 3:17:49 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsNewsBestSchoolProgram generated by hbm2java
 */
@Entity
@Table(name = "us_news_best_school_program", catalog = "School")
public class UsNewsBestSchoolProgram implements java.io.Serializable {

	private static final long serialVersionUID = -9584290758320L;
	private UsNewsBestSchoolProgramId id;
	private int rank;

	public UsNewsBestSchoolProgram() {
	}

	public UsNewsBestSchoolProgram(UsNewsBestSchoolProgramId id, int rank) {
		this.id = id;
		this.rank = rank;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schoolId", column = @Column(name = "School_Id", nullable = false)),
			@AttributeOverride(name = "programId", column = @Column(name = "Program_Id", nullable = false)) })
	public UsNewsBestSchoolProgramId getId() {
		return this.id;
	}

	public void setId(UsNewsBestSchoolProgramId id) {
		this.id = id;
	}

	@Column(name = "Rank", nullable = false)
	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	@Override
	public String toString() {
		return "UsNewsBestSchoolProgram [id=" + id + ", rank=" + rank + "]";
	}
	
	
	

}
