DROP TABLE IF EXISTS a_schools_for_b_students;
CREATE TABLE a_schools_for_b_students
(
  School_Id INT NOT NULL,
  School_Name VARCHAR(80),
  Primary Key (School_Id),
  FOREIGN KEY (School_Id) REFERENCES school (Id)
);

Insert a_schools_for_b_students values(55, 'Pepperdine University');
Insert a_schools_for_b_students values(66, 'Purdue University-West Lafayette');
Insert a_schools_for_b_students values(51, 'Syracuse University');
Insert a_schools_for_b_students values(69, 'Fordham University');
Insert a_schools_for_b_students values(76, 'Baylor University');
Insert a_schools_for_b_students values(59, 'Rutgers, the State University of New Jersey-New Brunswick');
Insert a_schools_for_b_students values(91, 'Clark University');
Insert a_schools_for_b_students values(75, 'Indiana University-Bloomington');
Insert a_schools_for_b_students values(72, 'Michigan State University');
Insert a_schools_for_b_students values(73, 'University of Delaware');
Insert a_schools_for_b_students values(96, 'University of Massachusetts-Amherst');
Insert a_schools_for_b_students values(70, 'Miami University-Oxford');
Insert a_schools_for_b_students values(107,'Texas Christian University');
Insert a_schools_for_b_students values(64, 'University of Iowa');
Insert a_schools_for_b_students values(84, 'Marquette University');
Insert a_schools_for_b_students values(88, 'University of Denver');
Insert a_schools_for_b_students values(90, 'SUNY College of Environmental Science and Forestry');
Insert a_schools_for_b_students values(80, 'University of Colorado-Boulder');
Insert a_schools_for_b_students values(106,'University of San Diego');
Insert a_schools_for_b_students values(98, 'University of Vermont');
Insert a_schools_for_b_students values(112,'Florida State University');
Insert a_schools_for_b_students values(83, 'St. Louis University');
Insert a_schools_for_b_students values(108,'Drexel University');
Insert a_schools_for_b_students values(111,'Loyola University of Chicago');
Insert a_schools_for_b_students values(118,'University at Buffalo-SUNY');
Insert a_schools_for_b_students values(142,'Auburn University');
Insert a_schools_for_b_students values(92, 'University of Missouri-Columbia');
Insert a_schools_for_b_students values(95, 'University of Nebraska-Lincon');
Insert a_schools_for_b_students values(109,'University of New Hampshire');
Insert a_schools_for_b_students values(114,'University of Oregon');
Insert a_schools_for_b_students values(86, 'Iowa State University');
Insert a_schools_for_b_students values(115,'University of Dayton');
Insert a_schools_for_b_students values(110,'University of Oklahoma');
Insert a_schools_for_b_students values(141,'University of San Francisco');
Insert a_schools_for_b_students values(113,'University of South Carolina');
Insert a_schools_for_b_students values(104,'University of the Pacific');
Insert a_schools_for_b_students values(124,'Clarkson University');
Insert a_schools_for_b_students values(130,'Duquesne University');
Insert a_schools_for_b_students values(129,'Temple University');
Insert a_schools_for_b_students values(85, 'University of Kansas');
Insert a_schools_for_b_students values(131,'University of St. Thomas');
Insert a_schools_for_b_students values(132,'University of Utah');
Insert a_schools_for_b_students values(133,'DePaul University');
Insert a_schools_for_b_students values(128,'Michigan Technological University');
Insert a_schools_for_b_students values(134,'Seton Hall University');
Insert a_schools_for_b_students values(125,'Colorado State University');
Insert a_schools_for_b_students values(135,'New School');
Insert a_schools_for_b_students values(127,'Arizona State University-Tempe');
Insert a_schools_for_b_students values(138,'Louisiana State University-Baton Rouge');
Insert a_schools_for_b_students values(137,'University at Albany-SUNY');
Insert a_schools_for_b_students values(126,'University of Arkansas-Fayetteville');
Insert a_schools_for_b_students values(136,'University of Illinois-Chicago');
Insert a_schools_for_b_students values(120,'University of Kentucky');
Insert a_schools_for_b_students values(139,'George Mason University');
Insert a_schools_for_b_students values(140,'Hofstra University');
Insert a_schools_for_b_students values(102,'Howard University');
Insert a_schools_for_b_students values(116,'Ohio University');
Insert a_schools_for_b_students values(143,'Oregon State University');
Insert a_schools_for_b_students values(144,'Rutgers, The State University of New Jersey-Newark');
Insert a_schools_for_b_students values(145,'University of Cincinnati');
Insert a_schools_for_b_students values(146,'University of Mississippi');
Insert a_schools_for_b_students values(123,'Kansas State University');
Insert a_schools_for_b_students values(151,'San Diego State University');
Insert a_schools_for_b_students values(152,'University of Alabama-Birmingham');
Insert a_schools_for_b_students values(153,'Adelphi University');
Insert a_schools_for_b_students values(155,'St. John-s University New York');
Insert a_schools_for_b_students values(156,'University of Maryland-Baltimore County');
Insert a_schools_for_b_students values(157,'University of Massachusetts-Lowell');
Insert a_schools_for_b_students values(158,'University of South Florida');
Insert a_schools_for_b_students values(159,'Virginia Commonwealth University');
Insert a_schools_for_b_students values(161,'Biola University');
Insert a_schools_for_b_students values(162,'Florida Institute of Technology');
Insert a_schools_for_b_students values(164,'Maryville University of St. Louis');
Insert a_schools_for_b_students values(165,'Mississippi State University');
Insert a_schools_for_b_students values(166,'University of Hawaii-Manoa');
Insert a_schools_for_b_students values(167,'University of Rhode Island');
Insert a_schools_for_b_students values(168,'Ball State University');
Insert a_schools_for_b_students values(169,'Texas Tech University');
Insert a_schools_for_b_students values(170,'University of Central Florida');
Insert a_schools_for_b_students values(172,'University of Louisville');
Insert a_schools_for_b_students values(174,'University of Wyoming');
Insert a_schools_for_b_students values(175,'Andrews University');
Insert a_schools_for_b_students values(176,'Azusa Pacific University');
Insert a_schools_for_b_students values(177,'Edgewood College');
Insert a_schools_for_b_students values(178,'Kent State University');
Insert a_schools_for_b_students values(179,'West Virginia University');
Insert a_schools_for_b_students values(183,'University of North Dakota');
Insert a_schools_for_b_students values(188,'University of Alabama-Huntsville');
Insert a_schools_for_b_students values(189,'University of Houston');
Insert a_schools_for_b_students values(198,'University of North Carolina-Charlotte');
Insert a_schools_for_b_students values(201,'Louisiana Tech University');
