package com.bedrosians.bedlogic.domain.item;
// Generated Jan 30, 2014 3:56:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * Ims generated by hbm2java
 */

@Entity(name="itemDetail")
@DynamicUpdate(value=true)
@SelectBeforeUpdate(value=true)
@Table(name = "ims", schema = "public")
public class ItemDetail extends Item implements java.io.Serializable {

	private static final long serialVersionUID = 674944990758702120L;
	@Embedded
	private Units units;
	@Embedded
	private Prices prices;
	@Embedded
	private Vendor vendor;
	@Embedded
	private PriorVendor priorVendor;
	@Embedded
	private Cost cost;
	@Embedded
	private SpecialHandleCode specialHandleCode;
	@Embedded
	private Alias alias;
	@Embedded
	Applications applications;
	@Embedded
	private SimilarItemCode similarItemCode;
	@Embedded
	private TestInfo testInfo;
	@Embedded
	private Notes notes;
	@Embedded
	private Miscellaneous miscellaneous;
	
	
	@Column(name = "itemgroupnbr", precision = 2, scale = 0)
	private Byte itemGroupNo;	
	@Column(name = "productline", length = 8)
	private String productLine;
	@Column(name = "directship", length = 1)
	private Character directShip;
	@Temporal(TemporalType.DATE)
	@Column(name = "dropdate", length = 13)
	private Date dropDate;	
	@Column(name = "leadtime", precision = 4, scale = 0)
	private Short leadTime;			
	@Column(name = "printlabel", length = 1)	
	private Character printlabel;
	@Column(name = "typealf", length = 8)
	private String typeAlf;
	@Column(name = "stdunit", length = 4)
	private String standardUnit;
	@Column(name = "stdratio", precision = 9, scale = 4)
	private BigDecimal starndardRatio;
	@Column(name = "ordunit", length = 4)
	private String orderUnit;
	@Column(name = "ordratio", precision = 9, scale = 4)
	private BigDecimal orderRatio;
	

	public ItemDetail() {
	}


	public Units getUnits() {
		return units;
	}


	public void setUnits(Units units) {
		this.units = units;
	}


	public Prices getPrices() {
		return prices;
	}


	public void setPrices(Prices prices) {
		this.prices = prices;
	}


	public Vendor getVendor() {
		return vendor;
	}


	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}


	public PriorVendor getPriorVendor() {
		return priorVendor;
	}


	public void setPriorVendor(PriorVendor priorVendor) {
		this.priorVendor = priorVendor;
	}


	public Cost getCost() {
		return cost;
	}


	public void setCost(Cost cost) {
		this.cost = cost;
	}


	public SpecialHandleCode getSpecialHandleCode() {
		return specialHandleCode;
	}


	public void setSpecialHandleCode(SpecialHandleCode specialHandleCode) {
		this.specialHandleCode = specialHandleCode;
	}


	public Alias getAlias() {
		return alias;
	}


	public void setAlias(Alias alias) {
		this.alias = alias;
	}


	public Applications getApplications() {
		return applications;
	}


	public void setApplications(Applications applications) {
		this.applications = applications;
	}


	public SimilarItemCode getSimilarItemCode() {
		return similarItemCode;
	}


	public void setSimilarItemCode(SimilarItemCode similarItemCode) {
		this.similarItemCode = similarItemCode;
	}


	public Notes getNotes() {
		return notes;
	}


	public void setNotes(Notes notes) {
		this.notes = notes;
	}


	public Byte getItemGroupNo() {
		return itemGroupNo;
	}


	public void setItemGroupNo(Byte itemGroupNo) {
		this.itemGroupNo = itemGroupNo;
	}


	public String getProductLine() {
		return productLine;
	}


	public void setProductLine(String productLine) {
		this.productLine = productLine;
	}


	public Character getDirectShip() {
		return directShip;
	}


	public void setDirectShip(Character directShip) {
		this.directShip = directShip;
	}


	public Date getDropDate() {
		return dropDate;
	}


	public void setDropDate(Date dropDate) {
		this.dropDate = dropDate;
	}


	public Short getLeadTime() {
		return leadTime;
	}


	public void setLeadTime(Short leadTime) {
		this.leadTime = leadTime;
	}


	public Character getPrintlabel() {
		return printlabel;
	}


	public void setPrintlabel(Character printlabel) {
		this.printlabel = printlabel;
	}


	public String getTypeAlf() {
		return typeAlf;
	}


	public void setTypeAlf(String typeAlf) {
		this.typeAlf = typeAlf;
	}


	public String getStandardUnit() {
		return standardUnit;
	}


	public void setStandardUnit(String standardUnit) {
		this.standardUnit = standardUnit;
	}


	public BigDecimal getStarndardRatio() {
		return starndardRatio;
	}


	public void setStarndardRatio(BigDecimal starndardRatio) {
		this.starndardRatio = starndardRatio;
	}


	public String getOrderUnit() {
		return orderUnit;
	}


	public void setOrderUnit(String orderUnit) {
		this.orderUnit = orderUnit;
	}


	public BigDecimal getOrderRatio() {
		return orderRatio;
	}

	public void setOrderRatio(BigDecimal orderRatio) {
		this.orderRatio = orderRatio;
	}
	
	public TestInfo getTests() {
		return testInfo;
	}


	public void setTests(TestInfo testInfo) {
		this.testInfo = testInfo;
	}


	public Miscellaneous getMiscellaneous() {
		return miscellaneous;
	}

	public void setMiscellaneous(Miscellaneous miscellaneous) {
		this.miscellaneous = miscellaneous;
	}
    
	
}
